"""Add static ||| detail to ALL remaining list items without detail."""

SEP = '|||'

DETAILS = {
  # Quiz options (Lesson 1)
  'The process of recruiting military personnel': 'This is military accessions — a separate function entirely. Defense acquisition specifically refers to how the government procures goods and services, governed by the FAR and DFARS, not personnel recruitment which falls under MILPERS and DoD Directive 1304.',
  'The system and rules governing how the U.S. government buys goods and services for national defense': 'Correct definition. The FAR (Federal Acquisition Regulation) is the primary rulebook, supplemented by the DFARS for DoD. Together they govern everything from office supplies to aircraft carriers — any purchase of goods, services, or R&D for national defense.',
  'The process of designing weapons systems': 'Weapons design falls under Research & Development (R&D) and Systems Engineering — distinct disciplines from acquisition. Acquisition is the process of buying what engineering has designed, though the two are closely linked in major defense programs.',
  "The military\\'s internal budgeting process": 'Internal budgeting is part of the PPBE (Planning, Programming, Budgeting, and Execution) process. Acquisition is the downstream activity of actually procuring goods and services once funding is appropriated by Congress — a related but distinct function.',

  # Single Award IDIQ
  'Typically used when the requirement is highly specialized and only one qualified source exists, or when a single integrated team is operationally necessary.': 'The government must justify a single-award IDIQ with a determination that multiple awards are not practicable — a high legal bar. Common examples: a program office that needs one fully integrated systems engineering support contractor, or a specialized capability where only one firm has the required past performance and security clearances.',
  'Example: A single contractor holding the USSOCOM systems engineering support contract.': 'SOCOM and other special operations commands often use single-award IDIQs for highly classified, mission-critical support work where contractor turnover would be operationally damaging. The incumbent advantage on recompete is enormous — and losing such a vehicle is a major business setback.',

  # MA-IDIQ
  'The dominant model for defense services: OASIS+, AFCAP, LOGCAP, agency-specific A&AS IDIQs.': 'OASIS+ (GSA) covers professional services government-wide. AFCAP (Air Force Contract Augmentation Program) and LOGCAP (Army Logistics Civil Augmentation Program) are major service-specific logistics and contingency support IDIQs. Agency-specific MA-IDIQs like USAFE A&AS V limit competition to named awardees for theater-specific requirements.',
  'Example: Eight contractors hold a $500M enterprise IT support IDIQ. Each task order RFP goes to all eight; they submit proposals; one wins.': 'This is the standard pattern for most defense services work. The government writes a task order SOW, issues it to all pool holders, evaluates proposals under simplified procedures (not full FAR Part 15), and awards to best value. Proposal turnaround is typically 7-30 days — much faster than a new contract competition.',

  # Players - PM and team
  "Program Managers (PMs) — The person accountable for a specific program. Responsible for cost, schedule, and performance. A PM\\'s job is to deliver the capability.": 'For ACAT I programs, the PM is typically an O-6 (Colonel/Navy Captain) or equivalent SES civilian. They hold a DAWIA Program Management certification and are personally accountable for executing within the Acquisition Program Baseline (APB). A PM who blows cost and schedule without early warning loses their program and often their career trajectory.',
  "Program Manager (contractor-side) — Once a contract is awarded, the contractor PM executes the work. Responsible for delivering on the contract, managing the team, tracking cost and schedule, and maintaining the customer relationship.": 'Contractor PMs manage the day-to-day: cost reports, deliverable schedules, subcontractor oversight, COR engagement, risk management. On cost-type contracts they submit monthly CPRs (Cost Performance Reports). Their biggest risk is scope creep — work the customer wants but the contract doesn\'t authorize.',
  "Contracts Manager — The contractor\\'s counterpart to the government CO. Manages the contract terms, handles modifications, REAs (Requests for Equitable Adjustment), and any disputes.": 'The Contracts Manager is the prime\'s legal agent on contract matters. They interpret FAR/DFARS clauses, draft modifications, prepare REAs when the government changes scope, and escalate claims if disputes arise. In cost disputes, they are the frontline against DCAA audit findings.',
  'Subcontractors — Companies hired by the prime to perform portions of the work. The prime is responsible for their performance and must flow down relevant contract requirements.': 'Flow-down clauses are critical — FAR 52.244-6 requires the prime to include certain clauses in all subcontracts. DFARS 252.244-7001 governs the prime\'s purchasing system. If a sub performs poorly, the government holds the prime accountable — the prime cannot deflect responsibility to the sub in CPARS or claims proceedings.',

  # Quiz options - who is MDA
  'The Program Manager': 'The PM executes the program but does not make milestone decisions for their own program — that would be a conflict of interest. The MDA is always above the PM in the chain: typically the PEO\'s chain for smaller programs and the SAE or USD(A&S) for ACAT I.',
  'The Program Executive Officer (PEO)': 'The PEO oversees the PM\'s program but is typically the MDA only for lower-tier programs (ACAT III or below). For ACAT I programs, the MDA is elevated to the SAE or USD(A&S). For ACAT II, the CAE (Component Acquisition Executive) is typically the MDA.',
  'The Contracting Officer (CO)': 'The CO awards and administers contracts but does not make acquisition milestone decisions. The CO is the legal agent for contracting actions; the MDA is the senior official who approves program advancement through the acquisition lifecycle phases.',

  # Color of money quiz options
  'The physical color-coding on budget documents to track spending': 'There is no physical color-coding system — "color of money" is entirely informal terminology. The actual mechanism is the appropriation type designation in the accounting system, which restricts what the funds can legally be spent on and when they must be obligated.',
  'The informal term for the type of appropriation, which determines what money can be spent on and how long it can be obligated': 'Correct. Different appropriations (RDT&E, Procurement, O&M, MILCON, MILPERS) each have specific authorized uses, obligation periods, and expenditure periods. Mixing them up is not a paperwork error — it\'s potentially an Anti-Deficiency Act violation with personal liability consequences.',
  'A reference to classified funding that cannot be discussed publicly': 'Classified or "black" programs do have special budget handling, but that\'s a separate concept from "color of money." Color of money refers to appropriation type restrictions that apply to all programs, classified or unclassified.',
  'The difference between authorized and appropriated amounts': 'Authorization and appropriation are two distinct Congressional actions — authorization establishes a program, appropriation provides funding. "Color of money" specifically refers to the type of appropriated funds and their permitted uses, not the gap between authorized and appropriated amounts.',

  # Finance module - regulatory framework
  'Title 10 U.S.C. — Statutory authority for defense acquisitions and armed forces': 'Title 10 provides the statutory foundation for DoD\'s authority to conduct acquisitions, organize the acquisition workforce (DAWIA), and govern major defense programs. Key sections: § 2304 (competition requirements), § 2306a (Truth in Negotiations Act/TINA), § 2433 (Nunn-McCurdy), § 4021-4022 (OTAs). When FAR and statute conflict, statute governs.',
  'FAR (Federal Acquisition Regulation) — Codified in 48 CFR, governs all federal procurement': 'The FAR is updated continuously through FAR cases — proposed rules published in the Federal Register, comment periods, and final rules. Subscription to FAC (Federal Acquisition Circular) notifications is how acquisition professionals stay current. The entire FAR is free at acquisition.gov. No one memorizes it — knowing how to navigate it quickly is the actual skill.',
  'DFARS — Defense-specific supplements; adds 200+ pages of DoD-specific rules': 'DFARS clauses are numbered 252.XXX vs FAR\'s 52.XXX. Key DFARS areas: 252.204-7012 (cybersecurity/CMMC), 252.225-7001 (Buy American), 252.215-7004 (excessive pass-through charges), 252.244-7001 (purchasing system). Each military service also has its own supplement (AFARS, NMCARS, AFFARS) adding another layer.',
  'DoDI 5000.02 — The "bible" for major system acquisitions, defines program phases': 'DoDI 5000.02 was replaced by the Adaptive Acquisition Framework (AAF) policy, which now lives across multiple DoDIs (5000.74, 5000.75, 5000.80, 5000.81, 5000.85, 5000.87). The old 5000.02 single-pathway model is gone — but the term "5000 series" still refers collectively to all these pathway-specific instructions.',
  'DODI 5000.74 — Governs Defense Acquisition of Services': 'DoDI 5000.74 applies to all service acquisitions above $10M and requires a Services Acquisition Strategy for those above $250M. It mandates portfolio reviews and senior official accountability. Services represent the largest share of DoD contract spending by volume — more than $200B annually.',
  'DODI 5000.75 — Governs Business Systems acquisitions': 'Business systems (financial, HR, logistics, acquisition IT) have unique acquisition considerations because they must comply with functional standards, integrate with existing DoD enterprise systems, and go through Investment Review Board (IRB) oversight. The Business Capability Acquisition Cycle (BCAC) replaces the traditional milestone structure for these programs.',

  # Appropriations types
  'RDT&E (Research, Development, Test & Evaluation) — 3-year availability; used to develop and test new systems': 'RDT&E has six budget activities: 6.1 (Basic Research), 6.2 (Applied Research), 6.3 (Advanced Technology Development), 6.4 (Advanced Component Development), 6.5 (System Development & Demonstration), 6.6 (Management Support). The budget activity number appears in all program budget exhibits and determines what specific development work is authorized.',
  'Procurement — 3-year availability; used to buy production-ready systems': 'Procurement funds buy end items in production quantities — aircraft, vehicles, ships, weapons. They cannot be used for development work (that\'s RDT&E) or for sustaining fielded systems (that\'s O&M). The 3-year availability means FY25 Procurement funds can obligate new contracts through September 2027, then enter a 5-year expired period for payment of existing obligations only.',
  'O&M (Operations & Maintenance) — 1-year availability; day-to-day operating costs and services': 'O&M is the workhorse appropriation — it pays for everything from base operations to most services contracts to contractor maintenance. The 1-year obligation period creates intense fiscal year-end pressure. The $250K threshold also matters: O&M cannot be used for construction that exceeds the MILCON threshold (generally $1.5M+).',
  'MILCON (Military Construction) — 5-year availability; construction of facilities': 'MILCON funds permanent construction, renovation, and real property acquisition. The 5-year availability reflects long project timelines. Using O&M for construction above MILCON thresholds is a common ADA violation — the line between "maintenance/repair" (O&M) and "construction" (MILCON) is frequently contested and often wrong in practice.',
  'MILPERS (Military Personnel) — 1-year; pay and allowances for uniformed personnel': 'MILPERS pays active duty military salaries, housing allowances (BAH), subsistence (BAS), hazardous duty pay, and separation pay. It cannot fund civilian positions (that\'s O&M) or contractor services. MILPERS accounts are among the most tightly controlled in DoD because Congress is extremely sensitive to military compensation issues.',

  # Cost estimating methods
  'Analogous (Top-Down): Uses historical data from similar programs. Fast but less accurate. Best for early phase estimates.': 'Analogous estimating takes a completed similar program and adjusts for size, complexity, and technology differences. RAND\'s DAPCA (Development and Production Cost Analysis) models are classic examples. Accuracy is typically ±30-50% — sufficient for budget formulation but not for contract negotiations. CAPE relies heavily on analogous methods for ICEs.',
  'Parametric: Uses Cost Estimating Relationships (CERs) — statistical models built from large databases of program data.': 'CERs express cost as a mathematical function of physical or performance parameters — e.g., cost = f(weight, speed, TRL). The SEER and PRICE parametric models are widely used in DoD. Parametric estimates can achieve ±15-25% accuracy when calibrated databases exist. They are particularly useful for novel systems where no single good analog exists.',
  'Engineering Build-Up (Bottoms-Up): Detailed task-by-task estimate. Most accurate but requires mature design and significant effort.': 'Bottoms-up estimates require a detailed WBS, labor category identification, hours per task, rates, and material costs. Accuracy can approach ±5-10% for mature programs. Contractors use bottoms-up for their proposals; government uses it to build the Independent Government Cost Estimate (IGCE). Requires significant estimating resources — typically 2-6 months for a major system.',
  'Hybrid approaches: Most programs use a combination — parametric for unknowns, bottoms-up for well-defined work packages.': 'A typical major acquisition uses bottoms-up for well-understood subsystems (existing designs), parametric for new development (using CERs calibrated to similar past programs), and analogous for system-level sanity checks. The estimating methodology must be documented and defensible to DCAA and CAPE review.',

  # Labor proposal review
  '1. Does the LCAT mix make sense for the statement of work? Senior engineers should not dominate routine tasks.': 'Labor Category (LCAT) mixing is one of the most common areas of over-proposal. A contractor proposing 80% senior engineers for help desk work is either building in margin or doesn\'t understand the requirement. The government should map each LCAT to specific SOW tasks and challenge any LCAT that doesn\'t align to the work described.',
  "2. Are the proposed direct labor rates consistent with the contractor\\'s disclosed forward pricing rate agreements (FPRAs)?": 'DCAA negotiates Forward Pricing Rate Agreements (FPRAs) with major contractors annually. These rates should be the ceiling for proposed direct labor. If a contractor proposes rates above their FPRA without explanation, that is a negotiation issue. Small businesses without FPRAs should be compared to market data (e.g., Bureau of Labor Statistics, salary surveys).',
  '3. For IDIQ/pre-priced vehicles: are the proposed rates at or below the contract ceiling rates? Any higher is non-compliant.': 'On pre-priced IDIQ task orders (where rates were established at vehicle award), the ceiling rates in the base contract are the maximum allowable. Proposing above ceiling rates is non-compliant and technically unacceptable — the CO should reject the proposal or require rate conformance before award.',
  '4. Is the contractor proposing the same LCATs they actually staff? Request key personnel resumes and verify qualifications.': 'Bait-and-switch is one of the most persistent problems in defense services contracting — companies propose impressive senior personnel to win, then staff with less qualified individuals. Key personnel clauses (requiring government approval for substitution) are a partial mitigation. Checking that proposed LCATs match the actual staffing plan is essential due diligence.',
  '5. What is the annual escalation rate applied to labor in out-years? Defense labor typically escalates 2.5-4% annually.': 'Labor escalation compounds significantly over multi-year contracts. A 5-year contract with 4% annual escalation on $10M year 1 labor reaches $12.2M in year 5 — a 22% increase. The government should verify escalation assumptions against published indices (Employment Cost Index, Defense-specific labor surveys) and challenge escalation rates above historical norms.',

  # What Makes a Successful PM
  'Deep understanding of the FAR/DFARS and acquisition regulations': 'A PM who doesn\'t understand FAR Part 15 (source selection), Part 16 (contract types), and Part 43 (modifications) will make decisions that create legal problems and protest risk. The PM doesn\'t need to be a lawyer, but must understand enough to know when to call one and to avoid unauthorized commitments.',
  'Ability to read and interpret financial reports (EVM, budget exhibits)': 'A PM who can\'t read a Cost Performance Report (CPR) or explain the difference between cost variance and schedule variance is flying blind. EVM data is the primary objective indicator of program health — understanding what it\'s telling you and what it isn\'t is a core PM competency.',
  'Experience managing contractor relationships and COR oversight': 'The PM sets the tone for the government-contractor relationship. Too adversarial and you get contractual warfare and claims. Too cozy and you lose objectivity on performance assessment. The PM should ensure CORs are properly trained, delegated, and actively monitoring — not just signing off on invoices.',
  'Skill in risk management and mitigation planning': 'Risk management in DoD programs means maintaining a live risk register, computing probability × impact scores, assigning risk owners, funding mitigation in the budget (Management Reserve), and tracking burn-down at program reviews. PMs who treat risk management as a checkbox exercise consistently get surprised by the risks they documented but didn\'t actively manage.',
  'Proficiency in requirements management and scope control': 'Requirements creep is a leading cause of program overruns. A PM must understand the approved requirements baseline (CDD/CPD) cold, recognize when contractor or government actions change scope, and ensure all scope changes go through formal contract modification. Informal scope direction — even from senior officials — that isn\'t contractualized creates constructive changes and claims.',
  'Stakeholder management across technical, financial, and leadership teams': 'A PM is the integrator of competing equities. The engineer wants more testing time. The finance analyst says you\'re out of money. The PEO wants the schedule. The contractor wants a modification. Managing these tensions without losing any stakeholder completely is the core PM leadership challenge.',
  'Understanding of the PPBE cycle to protect program funding': 'Programs that don\'t advocate effectively in the PPBE process lose funding to programs that do. A PM needs to understand how to build and defend a POM submission, what a Budget Change Letter (BCL) is and when to use one, and how Congressional markup affects their budget line. Passive PMs get their money taken.',

  # CO skills
  'FAR/DFARS mastery — understands what the regulations require and where flexibility exists': 'COs are warrant holders — their authority derives from their understanding of the regulatory framework. A CO who misapplies a FAR clause creates a defective solicitation that triggers protests. One who knows where the regulations allow flexibility (e.g., limited-competition justifications, streamlined procedures) can move programs faster while staying legally defensible.',
  'Negotiation skills — ability to drive fair and reasonable pricing without litigation risk': 'CO negotiations must result in a "fair and reasonable" price determination documented in the price negotiation memorandum (PNM). The CO must balance getting a good deal for the government against pricing the contractor into a loss position that triggers default or claims. This requires genuine business judgment, not just regulatory compliance.',
  'Business acumen — understands contractor cost structures, profit motives, and market dynamics': 'COs who understand that a contractor\'s fully burdened labor rate includes fringe, overhead, and G&A — not just salary — negotiate more effectively and make better contract type decisions. Understanding industry economics also helps COs identify when a proposal is unrealistically low (likely to lead to disputes) or inflated (requiring harder negotiation).',
  'Legal judgment — recognizes unauthorized commitments, organizational conflicts of interest, and protest risks': 'Unauthorized commitments — when a government employee without contracting authority directs contractor work — create major legal and financial problems. The CO must prevent them before they happen and ratify them correctly when they do. OCI recognition and mitigation is also critical; an OCI that isn\'t identified early can invalidate an entire source selection.',
  'Writing precision — contract language must be unambiguous and legally defensible': 'Ambiguous contract language is the most common source of claims. If the SOW can be read two ways, the contractor will read it the way that supports more money. Every clause, performance standard, and deliverable description should have a single clear interpretation that both parties agree to before award.',
  'Series 1102 federal position + DAWIA Contracting certification (Foundational, Practitioner, Advanced)': 'The 1102 series is the career field designation for government contracting specialists. DAWIA (Defense Acquisition Workforce Improvement Act) certifications at three levels are required for career progression. The contracting warrant — which grants actual authority to obligate the government — is issued separately by the Head of Contracting Activity based on demonstrated competence and certification.',
  'FAC-C certification (for civilian agencies); warrant issued by the Head of Contracting Activity (HCA)': 'FAC-C (Federal Acquisition Certification in Contracting) is the civilian agency equivalent of DAWIA for contracting. DoD primarily uses DAWIA. Both certification paths require coursework, experience, and continuous learning. The contracting warrant is the specific legal authority granted to an individual CO — it specifies the dollar threshold up to which they can independently sign contracts.',

  # COR skills
  "Deep technical knowledge of the contracted work — the COR must understand what \\\"good\\\" looks like": 'A COR who can\'t evaluate whether a deliverable meets the standard is useless as a quality monitor. The CO selects CORs for their technical expertise in the contracted area. A COR for an IT services contract needs IT knowledge; a COR for a systems engineering contract needs systems engineering background. Generalist CORs on technical programs are a serious program risk.',
  'Documentation discipline — maintains a contract file with dated records of every interaction with the contractor': 'COR files become critical evidence in disputes, protests, and CPARS challenges. Courts and boards of contract appeals look at contemporaneous records to determine what the parties understood, agreed to, and performed. COR files with gaps, undated entries, or vague summaries consistently disadvantage the government in adversarial proceedings.',
  'Scope awareness — instantly recognizes when a contractor request or government action would change contract scope': 'Scope creep often starts subtly — a senior government official asks the contractor to "just take a look at" something outside the contract. The COR\'s job is to flag these immediately and route them to the CO for a formal modification before any work begins. Unauthorized scope direction is a constructive change, and the COR who allows it creates government liability.',
  'Mandatory COR training (CLC 106 via DAU) and formal written appointment letter from the CO': 'Without the written appointment letter, the COR has no legal authority. The letter specifies the contract number, the COR\'s authorized duties, what they cannot do (direct changes, commit funds), and reporting requirements to the CO. Losing the appointment letter or failing to update it when contracts are modified is a common administrative gap that creates legal exposure.',
  'Independence — comfortable escalating contractor performance problems even when there is political pressure to look the other way': 'COR independence is often tested on high-visibility programs where leadership wants good news. A COR who whitewashes a CPARS rating because the contractor has friends in high places, or who accepts a marginal deliverable to avoid conflict, is failing their primary function. The COR\'s obligation is to the contract and the government — not to the contractor relationship.',
  'CORs must be a government employee (military or civilian) — contractors cannot serve as CORs': 'This is a fundamental inherently governmental function restriction. A contractor serving as a COR would be overseeing another contractor\'s performance — an obvious conflict. Some programs improperly rely on contractor "COR support" to supplement understaffed government COR functions; this must be structured as advisory only, never as actual COR authority.',

  # Financial Manager skills
  "Appropriations law fluency — understands the \\\"color of money\\\" rules and what each fund type can legally pay for": 'Financial managers are the program office\'s first line of defense against ADA violations. They must know not just what each appropriation type covers, but the nuances: the bona fide needs rule, the severable vs. non-severable services distinction for multi-year O&M contracts, and when a modification requires new funding vs. can be executed under existing obligations.',
  'PPBE cycle expertise — knows how to build a winning POM submission and defend it through the budget review process': 'The Program Objective Memorandum (POM) is the primary document through which programs compete for future funding. A weak POM submission — one that doesn\'t clearly articulate capability gaps, risk of under-funding, and compelling program performance — loses funding to programs that advocate more effectively. The FM must understand the OSD budget review process and how to respond to Program Budget Decisions (PBDs).',
  'EVM literacy — can read a CPR/IPMR and identify early indicators of cost growth': 'Financial managers translate EVM data into budget implications. A declining CPI trend means the EAC is growing — which means the program will need more money than currently appropriated. Identifying this 12-18 months out gives leadership time to find additional funding or make scope decisions. Identifying it at the end of the fiscal year creates a crisis.',
  'Anti-Deficiency Act (ADA) awareness — recognizes obligations that exceed available funding before they happen': 'ADA violations are reported to Congress and OMB. They can result in administrative discipline and criminal prosecution. Common traps: obligating a multi-year services contract against single-year O&M funds without severable services analysis; continuing a contract modification after funds expire; over-obligating a contract line. The FM must know these risks and build in controls.',
  'CDFM (Certified Defense Financial Manager) or DAWIA FM certification strongly preferred': 'CDFM is administered by the American Society of Military Comptrollers (ASMC) and is widely respected in the defense financial management community. DAWIA FM certification is the DoD-specific track. Both require demonstrated experience and competency. For GS-0501 financial management positions, FM certification is increasingly required for promotion above GS-12.',
  'Works closely with the PM and CO — no contract mod should be signed without FM confirming funds are available and correctly typed': 'This three-way coordination (PM/CO/FM) is the essential check on fiscal integrity. The PM wants the modification executed. The CO needs to verify it\'s legally proper. The FM must confirm that the right color of money is available in the right amount before the CO signs. When this coordination breaks down — usually under time pressure — ADA violations result.',

  # IDIQ ordering
  'Step 4: Provide fair opportunity — all pool members get a reasonable chance to compete': 'Fair opportunity under FAR 16.505 is the default rule — it cannot be waived without documented justification. The ordering CO must ensure the task order RFP is distributed to all eligible pool holders simultaneously with equal response time. Selectively notifying preferred contractors or providing advance information to favorites is a protest-sustaining violation.',
  'Step 5: Evaluate task order proposals (simplified process vs. full source selection)': 'Task order evaluations are significantly lighter than full Part 15 source selections — no formal discussions, no SSAC, fewer documentation requirements. But the process must still be documented, consistent with the stated evaluation factors, and defensible. Task order award decisions are still protestable to the GAO.',
  'Step 6: Award task order to the best value offeror': 'Best value means the proposal offering the greatest combination of technical merit, past performance, and price for the government\'s needs — not necessarily the lowest price. The ordering CO documents the tradeoff rationale. For LPTA task orders, the lowest technically acceptable price wins. Most professional services use BVTO.',
  'Step 7: Execute work; administer the task order like a standalone contract': 'Task orders have their own period of performance, deliverables, and COR. The COR monitors performance against the task order PWS/SOW, not just the base contract. Performance is documented in CPARS at the task order level for large orders. Option years on the task order can be exercised independently of the base contract.',
  'Step 8: Modify the task order (not the base contract) for scope/funding changes': 'Task order modifications use the SF-30 and follow the same modification authorities as standalone contracts. Critically — changes go on the task order, not the base IDIQ contract. Adding scope beyond the task order ceiling requires a new modification with additional funding. The base IDIQ contract is modified only for vehicle-level changes (period of performance extension, ceiling increase).',

  # OASIS+ ordering
  'Note: GSA charges an Industrial Funding Fee (IFF) or similar fee on OASIS+ orders': 'The IFF is currently 0.75% of the total task order value on OASIS+. Contractors remit the IFF to GSA; in practice, most build it into their pricing. Ordering agencies should factor this into their price analysis. The IFF funds GSA\'s contracting support infrastructure. Failing to account for IFF in price reasonableness determinations is a common oversight.',

  # Source selection steps
  'Step 3: Issue Draft RFP — industry review and comment period (30-45 days typical)': 'Draft RFP releases are best practice for complex acquisitions. Industry comments improve clarity, identify unrealistic requirements, and reduce protest risk. The government reviews all comments and provides a written responses or incorporates changes. Programs that skip draft RFP release often face more protests and more scope ambiguity post-award.',
  'Step 4: Issue Final RFP — proposals due date typically 45-60 days out': 'Proposal preparation time must be adequate for the complexity of the requirement. FAR 5.203 recommends minimum 30 days for large/complex acquisitions. Tight timelines disadvantage smaller firms without large proposal teams and increase the risk of non-compliant proposals from otherwise qualified contractors.',
  'Step 5: SSEB Evaluation — each proposal scored against stated evaluation factors': 'The Source Selection Evaluation Board (SSEB) applies the stated evaluation criteria consistently across all proposals. Each evaluator documents their findings with specific references to proposal content. Undocumented findings, subjective assessments without proposal citations, and inconsistent application of criteria are the most common protest-sustaining evaluation errors.',
  'Step 6: Competitive Range Determination — eliminate clearly unacceptable proposals': 'The competitive range includes all proposals that have a reasonable chance of award. Excluding a proposal from the competitive range is a significant decision — it ends that offeror\'s participation. The CO documents the rationale. Offerors excluded from competitive range are entitled to a post-exclusion debriefing.',
  'Step 7: Discussions (if applicable) — exchanges with offerors in competitive range': 'Discussions (different from clarifications) allow the government to identify deficiencies and weaknesses and give offerors a chance to revise. If discussions are opened with any offeror, they must be opened with all offerors in the competitive range. The CO must not engage in auction-style negotiations or reveal competitor pricing.',
  'Step 8: Final Proposal Revisions — offerors submit best and final offers (BAFOs)': 'After discussions, the CO issues a Final Proposal Revision (FPR) request establishing a common deadline for all offerors to submit their best revised proposals. Offerors can only improve proposals — they cannot worsen terms or retract revisions already submitted. This is typically the highest-pressure phase of the source selection.',
  'Step 9: SSAC Review — advisory recommendation to the SSA': 'The Source Selection Advisory Council (SSAC) reviews the SSEB findings and prepares an independent comparative assessment with a recommended award decision. The SSAC is advisory only — the SSA is not bound by the recommendation. For large acquisitions, the SSAC provides a valuable independent check on evaluation consistency.',
  'Step 10: SSA Award Decision — documented source selection decision statement': 'The Source Selection Decision Document (SSDD) is the legal foundation for the award. It must document the rationale for each significant tradeoff — why the technical advantages of the selected offeror justify any price premium over a lower-priced alternative. A weak SSDD is the government\'s most common vulnerability in bid protests.',

  # COR responsibilities
  'Notify the CO immediately of any performance deficiencies, schedule slips, or scope issues': 'The COR\'s notification obligation is immediate and in writing — verbal notifications don\'t create a legal record. The CO needs the documented notification to issue cure notices, show cause letters, or contract modifications. CORs who delay notification to avoid conflict give contractors time to dig deeper into performance problems.',
  'Maintain a surveillance plan and daily/weekly surveillance records': 'The Quality Assurance Surveillance Plan (QASP) defines how the COR monitors performance — what gets inspected, how often, and what the acceptance criteria are. Surveillance records must be detailed enough to support CPARS ratings and claims resolution. Spotty or absent records consistently disadvantage the government in disputes.',
  'Never direct the contractor to do work not in the contract scope — that creates constructive changes': 'A constructive change is a government-directed change to the contract that occurs without a formal modification. If the COR tells the contractor to "just add this" without CO authorization, the contractor may have a valid claim for additional compensation. The COR has no authority to change scope — only the CO does.',
  'Track invoices against actual work performed; do not accept invoices for work not completed': 'Invoice acceptance is a COR responsibility on many contracts. Accepting an invoice for work not performed or not accepted is improper payment — potentially a False Claims Act issue. The COR must verify deliverables are accepted, work is performed as described, and hours/materials are accurate before recommending payment.',

  # A&AS subcategories
  'Management and Professional Support Services — program management support, financial management consulting, and organizational studies': 'This subcategory covers program office support contracts — the analysts, program managers, financial advisors, and organizational consultants that work alongside government personnel. These are among the most sensitive A&AS contracts because contractors are often deeply embedded in government decision-making processes, raising inherently governmental function concerns.',
  'Studies, Analyses, and Evaluations — research, assessments, analytical work products, independent evaluations': 'This covers FFRDC-type work performed by for-profit contractors: alternatives analyses, cost-benefit studies, program assessments, policy research. Contractors in this space must be especially careful about organizational conflicts of interest — if you evaluate a program for which your parent company is also bidding, that\'s a textbook OCI.',
  'Engineering and Technical Services — support to acquisition programs including systems engineering, technical advice, and test support': 'This is the largest A&AS subcategory by dollar volume. SETA (Systems Engineering and Technical Assistance) contracts provide integrated engineering support to program offices. SETA contractors often have significant influence over requirements and acquisition strategy — which makes OCI management critical and inherently governmental function boundaries essential to enforce.',
  'A&AS-D (Digital) — emerging Air Force/Space Force category covering digital engineering, DevSecOps support, and digital transformation advisory': 'A&AS-D reflects the DAF\'s push toward digital-first acquisition. Contractors must demonstrate Platform One familiarity, IL4/IL5 cloud delivery experience, and DevSecOps credentials. This category is growing rapidly — contractors without demonstrated digital engineering credentials are increasingly finding traditional A&AS work difficult to retain on recompete.',

  # Base-level BD
  "Identify the installation contracting squadron through the Air Force\\'s Installation directory or SAM.gov agency searches. Every installation with a significant contracting footprint has a publicly accessible contracting office.": 'The Air Force Installation and Mission Support Center (AFICC) website and SAM.gov both list contracting office locations and contact information. Before investing BD resources at a base, verify the contracting office has authority over the types of requirements you pursue. Base contracting handles simplified acquisitions; large enterprise requirements route through ESS offices.',
  'Attend base-level small business events and installation open houses. Base contracting squadrons actively engage with industry — especially small businesses — in ways that larger enterprise offices cannot.': 'Small Business Day events and Industry Days at bases are among the highest-ROI BD activities for small businesses. You meet the CO, the contracting officers, and often the technical requirements owners in the same room. The program manager who remembers your company from a base event is far more likely to include you in market research for the next requirement.',
  'Build relationships with Contracting Officer Representatives (CORs), not just Contracting Officers. The COR is your day-to-day performance evaluator and one of the most influential voices in CPARS ratings and recompete positioning.': 'CORs write performance observations that feed directly into CPARS. They also influence future requirements by describing what the current contractor does well or poorly. A contractor who invests in COR relationship management — proactive status reporting, documenting issue resolution, making the COR look good to leadership — consistently outperforms competitors who treat the COR as a contract monitor rather than a strategic relationship.',
  'Focus on performance above all else. At the base level, your reputation spreads rapidly. A single strong CPARS rating from a base installation can be leveraged across the entire AFICC enterprise.': 'CPARS ratings are portable competitive assets. Exceptional ratings from base-level work become past performance references in ESS and MAJCOM-level source selections. The defense contracting community at any given installation is small — reputation spreads through the contracting officer network faster than through formal channels.',

  # Leading/lagging indicators
  'Leading (predictive): Staffing levels, test asset availability, GFE/GFI delivery status, risk burn-down': 'Leading indicators let you intervene before problems become cost and schedule variances. If staffing is at 70% of plan in month 3, you have a problem that will show up in the EVM data in month 5 — but only if you\'re tracking staffing now. GFE/GFI delays are another classic leading indicator: if the government is late delivering test equipment, the schedule impact arrives weeks later.',
  'Lagging (historical): CPI, SPI, defect count, actual vs. planned milestones, budget execution rate': 'CPI and SPI are the most common lagging indicators — they tell you what already happened. A CPI of 0.87 means 13 cents of cost overrun for every dollar of work accomplished, confirmed. This is valuable diagnostic information but it describes the past. Leading indicators are what let you change the future.',
  'Best practice: Track both — lead indicators give you time to act; lagging indicators confirm trends': 'The most effective program dashboards show both: leading indicators on the left (staffing, risk burn-down, GFE/GFI status) and lagging metrics on the right (CPI trend, SPI, milestone performance). This combination gives the PM a complete picture — what\'s happening now and what the trajectory suggests.',
  "Red flag: If ALL your metrics are lagging, you\\'re managing by looking in the rear-view mirror": 'Programs that report only CPI, SPI, and milestone completion are essentially confirming problems after they occur. By the time a CPI of 0.85 appears in the data, the root cause events happened 60-90 days earlier. A PM with only lagging indicators is always reacting, never anticipating.',

  # PM visualization tools
  'S-Curve: Cumulative BCWS vs. BCWP vs. ACWP — the fundamental EVM visualization. Any divergence between lines signals cost or schedule problems.': 'The S-Curve gets its name from the characteristic shape of cumulative spending on a program — slow start, acceleration through EMD, plateau in production. BCWS (Budget Cost Work Scheduled) is the plan line. BCWP (Budget Cost Work Performed) is actual progress. ACWP (Actual Cost Work Performed) is actual spending. BCWP below BCWS = schedule slip. ACWP above BCWP = cost overrun.',
  'Gantt/IMS Bar Chart: Timeline view of all program activities, dependencies, and critical path. Updated weekly in effective programs.': 'The Integrated Master Schedule is the Gantt chart on steroids — it shows every work package, milestone, and dependency relationship. The critical path is the longest path through the network from start to finish; any delay on the critical path delays the program end date by the same amount. Weekly schedule scrubs should focus on critical path tasks first.',
  'Risk Matrix (5×5): Plot all risks by probability and impact. Shows at a glance where attention is needed.': 'The 5×5 risk matrix scores each risk from 1-5 on probability and 1-5 on impact, creating a 25-cell grid. High-probability/high-impact risks in the upper right require immediate mitigation action and management reserve. The matrix should be updated monthly and briefed at every program review — a static risk matrix is a sign of a program that isn\'t actively managing risk.',
  'Burn Rate Chart: Monthly and cumulative obligation vs. plan. Reveals execution patterns.': 'Burn rate (obligation rate) is closely watched by Congressional staffers and OSD budget reviewers. Programs that obligate significantly below plan face "use it or lose it" pressure at fiscal year end — or lose funding in the next POM cycle. Programs that overoblate early may have cash flow problems later. The burn rate chart shows both and makes the pattern visible.',
  'TPM Trend Chart: Actual technical parameter values vs. planned maturity profile over time.': 'Technical Performance Measures (TPMs) track how actual system performance is maturing relative to planned development. If the radar range KPP calls for 300km detection at CDR and you\'re at 180km with 6 months to go, the TPM chart shows that trajectory clearly. TPMs are the early warning system for technical risk that will eventually become cost and schedule risk.',
  'Waterfall/Variance Chart: Decompose cost variance by work package or contractor to identify root cause.': 'Variance analysis is the "so what" of EVM data. A $5M negative cost variance is useless information without knowing which work packages are driving it, why, and what the PM is doing about it. The waterfall chart breaks the total variance into its components — showing, for example, that 80% of the cost overrun is in the propulsion subsystem due to a specific technical challenge.',

  # Capture plan components
  'Customer profile: Who are the decision-makers? What do they care about most?': 'Decision-maker mapping is BD fundamentals. The person who signs the contract (CO) is rarely the same as the person who defines requirements (program office) or evaluates proposals (SSEB). The capture manager must map all three layers — and track their priorities, concerns, and relationship with potential competitors. A capture plan without a contact matrix is incomplete.',
  'Competitive analysis: Who will bid? What are their strengths and vulnerabilities?': 'Competitive analysis ("Black Hat" in proposal parlance) means honestly assessing what your competitors will propose. What past performance will they cite? What technical approach will they take? Where are they weak? This analysis should inform your win themes — where you are genuinely superior — and your proposal strategy. Ignore competitive intelligence at your peril.',
  'Win themes: 3-5 compelling reasons why your solution is the best choice for this customer': 'Win themes are the narrative spine of the proposal. They must be customer-focused (not company-focused), specific (not generic), and defensible (tied to actual capabilities or past performance). "We have extensive experience" is not a win theme. "Our 12-year incumbent team reduced program operating costs 18% through proactive supply chain management" is a win theme.',
  'Discriminators: What can your firm do that competitors cannot? (or do demonstrably better)': 'Discriminators are the specific capabilities, past performance outcomes, team members, methodologies, or tools that set your firm apart. They must be real — evaluators are sophisticated and will challenge vague claims. The best discriminators are things that are verifiable (cited in existing CPARS, demonstrated in past deliverables, or evident from key personnel experience).',
  'Team strategy: Prime vs. sub; which partners add capability, contract vehicles, or customer relationships?': 'Teaming strategy is a competitive lever. The right sub brings: (1) specific technical capability the prime lacks; (2) a socioeconomic designation that meets a set-aside requirement; (3) a vehicle position (e.g., OASIS+ or relevant agency IDIQ); (4) existing customer relationships and past performance. The wrong sub adds overhead, dilutes the narrative, and creates performance risk.',
  "Price-to-win (PTW): What price position will win? (Not your cost — the price that wins)": 'PTW analysis works backward from the competitive landscape. What are competitors likely to propose? What does the government\'s IGCE suggest as their budget target? What price point would result in award? PTW is then compared to your internal cost estimate — if PTW is below your costs, you have a strategic decision about whether and how to bid. PTW analysis should drive cost reduction efforts, not just document a gap.',
  "Risk assessment: What could derail this capture? What\\'s the mitigation?": 'Capture risk assessment identifies the factors that could prevent award: incumbent advantage, competitor with better past performance, pricing below market, requirement written around a competitor\'s solution, internal resource constraints during proposal. Each risk should have a mitigation action — shaping the requirement through industry engagement, building a stronger team, investing in price reduction.',

  # Proposal anatomy
  'Executive Summary: State your win themes and discriminators upfront — 2 pages maximum': 'The executive summary is often the only section some evaluators read in full. It should state your top 3-4 win themes, demonstrate understanding of the government\'s key challenges, and compel the reader to want to know more. Do NOT summarize the proposal structure ("Section 2 covers our management approach..."). Lead with value, not organization.',
  'Technical Approach: Describe HOW you will solve the problem — specific, not generic': 'The most common technical volume failure is writing about what you will do rather than how you will do it. "We will provide experienced program management support" is generic. "Our PM will establish a weekly IPT cadence aligned to the government\'s existing review schedule, using our Earned Value reporting template from the USAFE A&AS V contract to provide identical visibility to that which the customer currently receives" is specific.',
  'Management Approach: How will you staff, manage, and deliver? Show your program management process': 'The management volume should demonstrate that you\'ve actually thought through execution — not just listed resumes and org charts. Include your quality management approach, staffing plan with timeline, transition plan (critical for incumbents and new entrants alike), and subcontractor management methodology. Evaluators are looking for risk — a thin management approach signals execution risk.',
  'Past Performance: Analogous contracts with measurable results — quality over quantity': 'One highly relevant CPARS "Exceptional" rating from a closely analogous contract outweighs five "Satisfactory" ratings from peripheral work. Past performance citations should map directly to evaluation factors — if the RFP emphasizes program management support, cite contracts where you provided PM support, not your unrelated IT work. Include measurable outcomes: cost performance, schedule adherence, customer satisfaction ratings.',
  'Price/Cost Volume: Realistic, well-supported pricing with clear assumptions': 'Unrealistically low pricing is a protest risk and an execution risk. If your price is significantly below the IGCE, the government may question your understanding of the requirement. Include clear pricing assumptions, escalation methodology, and a staffing plan that matches your technical approach. For cost-type contracts, your cost proposal will be subject to DCAA review — ensure your accounting system can support the rates proposed.',
  'Compliance Matrix: Every Section L requirement mapped to your proposal response': 'The compliance matrix is both a proposal tool and a management tool. Before you submit, the compliance matrix should show a green checkmark for every Section L requirement — format, page limits, content requirements, certifications. Proposals that miss a Section L requirement (e.g., required certifications, resume format, page limits) can be found technically unacceptable regardless of content quality.',

  # Pipeline discipline (second occurrence)
  'Minimum 18-month horizon: opportunities should enter your pipeline at least 18 months before RFP, giving you time to shape requirements, build relationships, and position your solution.': 'Opportunities that enter the pipeline at RFP release are already shaped by the incumbent and by competitors who engaged earlier. By the time the solicitation is on SAM.gov, the smart money has already engaged with the program office, responded to the RFI, attended the industry day, and influenced at least some evaluation criteria. Late entrants compete at a structural disadvantage.',
  'pWin gate: no opportunity proceeds to active capture without a documented pWin assessment. Typical thresholds: below 25% = watch only; 25–50% = selective investment; above 50% = full capture investment.': 'pWin is both an assessment and a management discipline. A firm that consistently pursues opportunities below 25% pWin is burning proposal resources and demoralizing its BD team. The pWin assessment should document: customer relationship quality, past performance relevance, competitive position, incumbent status, and team strength. Unsubstantiated "gut feel" pWin estimates are not a management tool.',
  'Vehicle alignment: every opportunity in the pipeline must map to a vehicle you hold or are pursuing. If you don\'t have the vehicle, pursuing the opportunity is premature.': 'Vehicle strategy is the infrastructure of pipeline strategy. If a requirement will be sourced through OASIS+ and you don\'t hold an OASIS+ position, you cannot bid regardless of how strong your solution is. Pipeline review should include a vehicle check for every opportunity — ensuring the firm either holds the vehicle, is pursuing it, or has an alternative path (teaming with a vehicle holder as a sub).',
  'Qualification criteria: define your "no bid" criteria before you see opportunities. Common no-bid signals include incumbent with strong CPARS, requirement written around competitor capabilities, and budget not yet appropriated.': 'No-bid decisions are as strategically important as bid decisions. Proposing on low-pWin opportunities has direct costs (proposal labor) and opportunity costs (those resources could have been on winnable bids). Pre-defined no-bid criteria prevent the political pressure to "just submit something" from overriding analytical judgment. Typical no-bid triggers: pWin below threshold, less than 15 days to proposal, no customer relationship, no relevant past performance.',

  # DCAA compliance
  'Timekeeping system: must capture time by contract/project daily, not estimated retroactively. DCAA requires contemporaneous timekeeping — this is non-negotiable.': 'DCAA\'s timekeeping standard is explicit: employees must record time on the day the work is performed, not reconstructed from memory at week\'s end. Systems that allow retroactive time entry without documented justification are flagged as inadequate. An inadequate timekeeping finding can result in withheld progress payments and loss of cost-type contract eligibility until corrected.',
  'Unallowable cost segregation: FAR 31.205 identifies numerous unallowable cost categories (entertainment, alcohol, certain lobbying, fines/penalties). These must be segregated in your accounting system.': 'FAR 31.205 has 47 cost principles covering what is and isn\'t allowable on government contracts. Common unallowable categories: entertainment (31.205-14), contributions/donations (31.205-8), executive lobbying (31.205-22), fines and penalties (31.205-15), and costs incurred in connection with fraud proceedings (31.205-47). These must be in separate accounting codes that are excluded from indirect rate pools and never billed to cost-type contracts.',
  'Written policies: compensation, travel, and overtime policies must be in writing and consistently applied. Verbal policies are invisible to auditors.': 'DCAA auditors ask for written policies on compensation, travel, overtime, and leave as a standard part of system reviews. "We always do it this way" or "everyone knows the policy" is not acceptable — if it\'s not written and documented, it doesn\'t exist from an audit perspective. Policies must also be consistently applied — paying one employee differently from another under the same policy creates audit questions.',
  'Indirect rate structure: your labor categories, overhead pools, and G&A base must align to how work is actually organized and priced. Misalignment creates audit findings.': 'The indirect rate structure (overhead pools, G&A base, fringe benefit rates) must be consistent with how costs actually flow. A company that has two separate locations should typically have two overhead pools. A company that does both commercial and government work must carefully structure its G&A base to avoid cross-subsidization claims. Rate structures that are set up for convenience rather than to reflect actual cost flows create DCAA findings that require expensive restructuring.',

  # Career roadmap - USG
  'Get your security clearance — many roles require Secret or TS/SCI; apply early': 'The clearance backlog has historically run 12-24 months for Secret and longer for TS/SCI. Starting the process at your first eligible opportunity — typically when you accept a conditional job offer — is critical. Any financial irregularities, foreign contacts, or drug use history should be disclosed honestly; the adjudication process is more forgiving of disclosed issues than discovered ones.',
  'Enroll at Defense Acquisition University (DAU) — free courses, essential credentials': 'DAU (dau.edu) is free for all DoD government employees and provides the DAWIA certifications required for career progression. Start with ACQ 101 (Fundamentals of Systems Acquisition Management) regardless of your career field. The continuous learning requirement (40 CLPs/year) keeps certifications current. DAU courses are also available to industry partners at a modest cost.',
  'Target USAJOBS.gov listings under series 1102 (Contracting), 0340 (PM), or 0501 (Financial)': 'USAJOBS.gov is the mandatory posting site for all federal civilian positions. Filter by occupational series, grade (GS-7 to GS-11 for entry), and location. Set up automated job alerts for your target series and locations. Pathways Recent Graduates positions are specifically designated — search for "Pathways" combined with your target series. Veterans\' preference points provide a meaningful advantage.',
  'Network at AFCEA, NDIA, and SAME events — the defense community is relationship-driven': 'AFCEA (Armed Forces Communications and Electronics Association), NDIA (National Defense Industrial Association), and SAME (Society of American Military Engineers) host local chapter events, symposia, and luncheons where government and industry professionals mix. Showing up consistently, engaging thoughtfully, and following up after meetings compounds into a professional network that accelerates both information and opportunity.',
  'Obtain a relevant certification: PMP, CDFM, CPCM, DAWIA equivalents': 'Certifications signal commitment and baseline competence. PMP (Project Management Professional) is recognized across both government and industry. CDFM (Certified Defense Financial Manager) is specific to defense finance. CPCM (Certified Professional Contracts Manager) is the NCMA standard for contracting professionals. DAWIA certifications are DoD-specific. The right certification depends on your target career field and employer.',
  'Build your resume around the FAR/DFARS, EVM, and program management language': 'Federal resumes are longer than private sector resumes (often 3-5 pages) and must include specific language from job announcements for keyword matching. Quantify achievements: "Administered 23 task orders totaling $47M" beats "managed multiple contracts." Use the exact terminology from the job announcement — applicant tracking systems match keywords before humans read resumes.',
  'Consider the Pathways Recent Graduates program if you recently completed a degree': 'The Pathways Recent Graduates Program accepts applications within 2 years of degree completion. It provides 1 year of structured career development, a mentor, and a clear pathway to a permanent appointment. It\'s one of the few structured entry pipelines for federal service and offers GS-7 to GS-9 starting grades depending on education and experience.',

  # Career roadmap - contractor
  'Identify target companies: Booz Allen, Leidos, SAIC, Peraton, BAH, GDIT, ManTech, DXC, HII (Huntington Ingalls), L3Harris': 'The "Big 8" defense services firms (Booz Allen, Leidos, SAIC, Peraton, GDIT, ManTech, CACI, Accenture Federal) collectively hold thousands of task orders across all DoD components. They offer structured career paths, training programs, and geographic diversity. Mid-size firms (200-2000 employees) often offer faster advancement and broader responsibility. Small businesses (<500 employees) offer equity potential and agility.',
  'Target roles: Program Analyst, Capture Analyst, Contract Support, Cost Analyst': 'Entry-level titles in defense contracting are deliberately general. Program Analyst is the most common entry point — supporting a PM or program office on a cost-reimbursable contract. Capture Analyst supports BD and proposal functions. Contract Support assists the Contracts department. Cost Analyst focuses on pricing and financial analysis. All four build toward PM, Capture Manager, Contracts Manager, or Finance Director tracks respectively.',
  'Build expertise in GovWin IQ, FPDS-NG, SAM.gov — essential tools for BD roles': 'GovWin IQ (Deltek) is the dominant competitive intelligence platform for defense contracting — used to track opportunities, incumbents, and award histories. FPDS-NG (Federal Procurement Data System-Next Generation) is the government\'s public procurement database — every contract award above the micro-purchase threshold is reported here. SAM.gov (System for Award Management) is where opportunities are posted and contractor registrations are maintained.',
  'Understand EVM — most contractor PM roles require EVMS knowledge': 'Earned Value Management System (EVMS) knowledge is now a near-universal requirement for contractor PM roles on cost-type defense contracts. Understanding how to structure a WBS, maintain a baseline, calculate variances, forecast EAC, and prepare IPMR/CPR reports is the core of program financial management. AACE International and PMI both offer EVM-related credentials.',
  'Leverage LinkedIn: connect with BD managers, capture managers, and proposal professionals': 'LinkedIn is the primary professional networking platform for defense contractors. Following companies, engaging with their content, and connecting with people in target roles creates visibility before formal job applications. Many BD and capture roles are filled through internal referrals — being known to the hiring manager before the job opens is the most reliable way in.',
  'Join APMP (Association of Proposal Management Professionals) — excellent community': 'APMP (apmp.org) has a robust local chapter network, certification program (Foundation, Practitioner, Professional levels), and an annual conference that is genuinely valuable for anyone in proposal management, BD support, or capture roles. The APMP Body of Knowledge is also a practical reference for proposal professionals at all experience levels.',

  # Problem solver mindset (in ops module)
  'Build bridges across silos: the contracting officer, the finance lead, and the engineer all need to know each other\'s world well enough to communicate effectively': 'The most effective program offices are integrated teams where each member understands adjacent functions well enough to anticipate problems across silos. A PM who can\'t explain EVM to the engineer or acquisition strategy to the finance lead is constantly translating — and losing information in translation. Cross-functional fluency is a force multiplier.',
  'Document decisions — when things go sideways, the paper trail protects you and the program': 'Every significant decision — to proceed despite a risk, to accept a deliverable with a known deficiency, to defer a test event — should be documented in writing with the reasoning. When OIG or GAO audits a struggling program, they look for decision documentation. Programs that made sound decisions but didn\'t document them look exactly like programs that made poor decisions.',
  "Ask \\\"so what?\\\" relentlessly — data without a so-what is noise, not insight": 'Program reviews that present data without interpretation — "our CPI is 0.91" — are missed opportunities. The PM should train the team to always provide context: "our CPI is 0.91, which represents a $3.2M cost overrun driven by three specific work packages, and we\'ve initiated recovery actions X, Y, and Z." Data that prompts a decision is useful. Data that just sits there is overhead.',
  'Treat every program review as a chance to demonstrate command of your program, not just read slides': 'Senior leaders — PEOs, SAEs, Congressional staffers — evaluate PM competence based on whether they can speak to their program without looking at the slides. PMs who know their numbers cold, who anticipate questions before they\'re asked, and who present problems with solutions already framed project a very different level of confidence than those who are reading the brief for the first time.',

  # Risk management process
  'Identify: Brainstorm risks across technical, cost, schedule, and programmatic domains': 'Effective risk identification is a team sport — the PM, CO, finance lead, engineers, and contractor each see different risks. Use structured facilitation (risk workshops, checklists from similar programs, lessons-learned databases) rather than relying on individual memory. Common missed risks: GFE/GFI delivery delays, single points of failure in key personnel, regulatory changes that affect requirements, and supply chain risks for electronic components.',
  'Analyze: Assess probability (1-5) and impact (1-5) for each risk, cost and schedule': 'Risk scoring must be honest, not optimistic. Programs that systematically under-score risks to avoid management attention end up with their "medium" risks materializing as program-killers. Use a defined scale with clear anchors — a probability of 3 should mean roughly 50% likelihood, not "vaguely possible." Cost and schedule impact should be quantified in dollars and days where possible.',
  'Plan: Develop mitigation strategies, owners, and timelines for high/medium risks': 'Every risk above the threshold should have: a mitigation owner (by name, not by title), specific mitigation actions with completion dates, and trigger conditions that would move the risk from "mitigation" to "contingency." Management Reserve (MR) should be budgeted to execute the contingency plan if mitigation fails. Underfunded MR is one of the most common structural problems in program risk management.',
  'Track: Update risk register monthly; show burn-down trends at program reviews': 'The risk register is a living document, not a one-time deliverable. At each program review, show which risks were retired, which new risks were added, and how the probability/impact scores have changed. A risk burn-down curve (total risk score over time) shows whether the program is getting safer or more dangerous. Flat or rising risk scores in production are a serious signal.',
  'Control: Execute mitigation actions, retire closed risks, elevate emerging risks': 'Risk control is where most programs fail — they identify and score risks thoroughly but don\'t hold owners accountable for mitigation execution. Monthly risk reviews should include mitigation action status: completed, on track, slipping. Slipping mitigation actions should be escalated to the PM immediately. Risks that were "closed" should be periodically reviewed — resolved risks have a way of re-opening when pressure increases.',
  'Opportunities: Actively manage positive risks (early tech maturation, cost savings)': 'Opportunity management is the mirror of risk management and is almost always neglected. Positive risks — a supplier delivering early, a test that validates performance above the KPP threshold, a design trade that saves $10M — should be actively exploited. The PM who discovers a cost savings opportunity and captures it in Management Reserve is in a much stronger position when a negative risk materializes.',

  # Stakeholder map
  'Program Executive Officer (PEO): Your direct superior; manages your portfolio and fights for your resources at the SAE level': 'The PEO is both your advocate and your evaluator. They fight for your program in POM deliberations, defend you in front of the SAE and OSD, and hold you accountable for performance. A PM who keeps their PEO informed and never surprises them with bad news builds the trust that translates into budget support during difficult reviews. A PM who hides problems loses their PEO\'s confidence — usually permanently.',
  'Service Acquisition Executive (SAE): Delegated authority over all acquisition programs for the Service; approves Acquisition Strategy for major programs': 'The SAE is a Senate-confirmed civilian (ASA(ALT), ASN(RDA), or SAF/AQ). They approve major acquisition strategies, chair ACAT I milestone reviews, and have direct visibility into Congressional relations for the service\'s acquisition portfolio. A PM briefing the SAE for the first time should expect hard questions about cost, schedule, and risk — and should be able to answer all of them without notes.',
  'USD(A&S): Ultimate DoD acquisition authority; sees ACAT I programs at milestone reviews': 'The Under Secretary of Defense for Acquisition and Sustainment oversees the entire DoD acquisition enterprise. For ACAT ID programs, USD(A&S) is the Milestone Decision Authority. At milestone reviews, USD(A&S) receives briefings from the program office, CAPE, DOT&E, and DCMA — each presenting their independent assessment. Programs that have managed these relationships proactively have fewer surprises at the table.',
  'Program Office Team: Engineers, logisticians, financial managers, contracting officers, CORs': 'The integrated program office team is the PM\'s most critical stakeholder group and most important accountability mechanism. A PM is only as effective as their team. Investing in team development, clearly defining lanes of responsibility, and creating a culture where people surface problems early rather than hiding them is the difference between a functional program office and a dysfunctional one.',
  'Combatant Commands: The warfighters who will use the system — their requirements drive everything': 'Combatant Commands (COCOMs) and their component commands are the ultimate customers — the people who will actually use the capability being acquired. PMs who lose sight of the warfighter and become consumed by internal DoD bureaucracy often find themselves delivering technically compliant systems that don\'t meet operational needs. Regular operational interface and user engagement throughout the program lifecycle is essential.',
  'Congressional Staff: Monitors programs on their committees; a single staffer can affect funding': 'Congressional staff on the HASC, SASC, HAC-D, and SAC-D are among the most powerful stakeholders in any major program — and the most underestimated by program offices. A single staffer who loses confidence in a program can insert reporting requirements, fund restrictions, or rescissions in legislation. PMs of ACAT I programs should know the key staffers by name and ensure their PEO is maintaining regular communication.',
  'Contractors: Partners in program execution; relationship management is critical': 'The PM-contractor relationship is a managed partnership, not an adversarial one. Programs where the government treats contractors purely as vendors to be squeezed consistently underperform — contractor innovation, proactive risk surfacing, and best-effort performance all improve when the relationship is collaborative. This doesn\'t mean being soft on performance — it means being clear about expectations, fair in evaluation, and honest about problems.',
  'OSD Cost / CAPE: Independent cost analysis; often skeptical of program office estimates': 'CAPE ICEs are almost always higher than program office estimates — and history shows CAPE is usually right. CAPE uses parametric models calibrated to historical program data rather than the optimistic assumptions that program offices naturally favor. PMs who engage CAPE early, share data proactively, and address CAPE\'s methodological concerns before the milestone review significantly reduce the "surprise" factor in the milestone briefing.',

  # Subcontract management plan
  'Identification of critical subcontractors and the make/buy strategy': 'Critical subcontractor identification should include: tier 1 subs responsible for major deliverables, single-source suppliers of critical components (especially electronic parts), and any sub whose failure would trigger a Nunn-McCurdy breach. The make/buy strategy documents what the prime builds internally vs. what gets purchased — government insight rights differ depending on which side of the line the work falls.',
  'Subcontract surveillance approach: how the prime monitors each major sub': 'Surveillance methodology should be risk-based — more intensive oversight for newer relationships, lower-performing subs, or higher-risk technical work. Government insight into subcontractor surveillance (via DCMA oversight of the prime\'s purchasing system under DFARS 252.244-7001) provides an additional check. Program offices should request surveillance reports and CPSR results as part of their prime contractor management.',
  'Frequency and format of subcontractor performance reviews': 'Monthly is the standard for major subcontracts. Reviews should include: EVM data at the sub level (if applicable), technical progress against milestones, staffing levels, risk status, and open action items. Program offices should attend or receive read-outs of prime-to-sub reviews for critical subcontractors — passively waiting for the prime to escalate problems is a recipe for late discovery.',
  'Flow-down clause requirements applicable to each subcontract tier': 'FAR 52.244-6 lists the clauses that must flow to commercial item subs. Many DFARS clauses also require flow-down — DFARS 252.204-7012 (cybersecurity) must flow to subs that handle covered defense information. Primes sometimes fail to flow required clauses, creating compliance gaps that DCMA and DCAA discover during audits. The SMP should specifically address which clauses flow to which sub tiers.',
  'Corrective action process when a subcontractor misses performance milestones': 'Corrective action should be escalating: informal notification → formal Corrective Action Request (CAR) → cure notice → show cause → termination for default. Each step requires documentation. The government\'s leverage comes through the prime — the government cannot direct subcontractors directly, but can pressure the prime through its contract administration tools to enforce the prime\'s contractual rights against its subs.',
  'Government insight mechanisms: data rights, audit access, review participation': 'Standard government insight into subcontractors flows through the prime: DCMA surveillance of the prime\'s purchasing system, prime-submitted IPMR/CPR data that includes sub EVM, and audit access through the prime\'s cost reporting. For critical subs, program offices sometimes negotiate direct insight rights in the prime contract — particularly for major development subcontracts where subcontractor performance is the dominant technical risk.',
  'Small business subcontracting plan goals and tracking methodology': 'Large primes on federal contracts above $750K must submit a Small Business Subcontracting Plan (FAR 52.219-9) with specific percentage goals for SB, SDB, WOSB, HUBZone, SDVOSB, and VOSB categories. Failure to make good faith efforts to meet plan goals can result in liquidated damages. Individual Subcontracting Reports (ISRs) and Summary Subcontracting Reports (SSRs) are filed semi-annually and annually in eSRS.',

  # Escalating sub issues
  'Step 1: Identify the issue through prime reporting or DCMA surveillance — document in writing': 'Never address subcontractor performance issues verbally only. The first step is written documentation: a letter or email to the prime PM identifying the specific performance deficiency, the contract requirement it violates, and the date it was first observed. This creates the paper trail that supports subsequent escalation steps and protects the government in any future claims proceeding.',
  'Step 2: Direct the prime PM (not the subcontractor directly) to develop a corrective action plan (CAP) within 15 days': 'The government contract is with the prime — not the subcontractor. All direction must flow through the prime. Contacting the subcontractor directly, even informally, creates unauthorized commitment risk and undermines the prime\'s contractual authority over its sub. The prime PM is responsible for the CAP content and for holding the sub accountable for executing it.',
  'Step 3: Set a hard CAP review deadline — 30 days maximum for critical issues': 'A CAP without a deadline is not a CAP — it\'s a promise. The 30-day deadline for critical issues creates management pressure on both the prime and sub. The review should assess: are the root causes correctly identified? Are the mitigation actions specific and executable? Is the recovery schedule credible? A vague CAP that says "we\'re working on it" should be rejected and a specific plan demanded.',
  'Step 5: If the prime fails to correct: formal cure notice or show cause letter issued by the Contracting Officer': 'A cure notice (FAR 49.607) gives the prime 10 days to cure a material breach before the government terminates for default. A show cause letter asks the prime to explain why the contract shouldn\'t be terminated. These are serious contractual actions that must be coordinated with legal counsel and the CO. Once issued, they cannot be easily walked back — they should be used deliberately, not as threats.',
  'Step 6: Consult with legal and CO on contract remedies if pattern of non-performance continues': 'Contract remedies range from partial termination (of the non-performing work package) to full termination for default, with potential liability for reprocurement costs. These decisions should never be made without legal and CO involvement. Termination for default can be converted to termination for convenience by a court or board — so the documented record of non-performance and government response must be airtight.',

  # Quiz option - wrong answer for sub management
  'Contact the subcontractor directly and direct them to accelerate': 'This is incorrect and potentially creates legal problems. The government\'s contract is with the prime, not the subcontractor. Directly directing the subcontractor — even informally — can create an unauthorized commitment, undermine the prime\'s contractual authority over its sub, and give the sub grounds to claim the government assumed responsibility for their performance. All direction must flow through the prime.',
  'Direct the prime contractor to develop a corrective action plan addressing the subcontractor delay': 'Correct. The government directs the prime (not the sub) to develop and execute a corrective action plan. The prime has contractual authority over its subcontractors and is responsible for their performance. The CAP should include root cause analysis, specific corrective actions, and a realistic recovery schedule that the prime will enforce with the sub.',

  # IMS best practice (last item)
  "Never let the IMS drift more than one reporting cycle from ground truth. A single reporting period of": 'This is the discipline that separates programs that manage schedule from programs that report it. When the IMS shows green but the program is amber, leadership makes decisions based on false data. The cost of updating the IMS to reflect reality (which feels painful) is always lower than the cost of having the real situation emerge as a surprise at a milestone review.',
  'Maintain a separate, honest internal view alongside any externally-formatted schedule. What you brief to oversight should be accurate — but your internal working view should include all known risks and their schedule impacts before they become public.': 'The "two schedule" concept is a practical reality on most major programs. The externally formatted IPMR/CPR schedule must be accurate and contractually compliant. The internal working view should include all the amber and red items that haven\'t yet hit the formal baseline — giving the PM the full picture needed to make decisions. The goal is not to hide problems but to solve them before they become baseline deviations.',

  # Requirements checklist (last item)
  'Has the requirements community (JROC for ACAT I) validated that this requirement is still current, fundable, and operationally relevant? Requirements that drift from validated documents without authorization create milestone review failures.': 'Requirements can become orphaned when the operational environment changes (new threats, new technology), when funding constraints force descoping, or when program maturity reveals that the original requirement was unrealistic. Any requirement that no longer appears in the validated CDD/CPD cannot be contractually required — and any contract requirement that isn\'t in the validated documents creates unauthorized scope. The requirements traceability matrix should be audited before every milestone.',
}

with open('client/src/lib/curriculum.ts') as f:
    content = f.read()

SEP = '|||'
count = 0
not_found = []

for item_text, detail in DETAILS.items():
    # Try single-quoted version
    old = f"'{item_text}'"
    new = f"'{item_text}{SEP}{detail}'"
    if old in content:
        content = content.replace(old, new, 1)
        count += 1
    else:
        # Try without trailing comma
        not_found.append(item_text[:60])

# Now handle items that are truncated in the file
# Find by first 40 chars and patch
import re

lines = content.split('\n')
updated_lines = []
remaining = {k: v for k, v in DETAILS.items() if f"'{k}'" not in content}

for i, line in enumerate(lines):
    stripped = line.strip()
    if SEP in line or not stripped.startswith("'"):
        updated_lines.append(line)
        continue
    
    matched = False
    for item_text, detail in list(remaining.items()):
        # Check if this line starts with the first 50 chars of the item
        prefix = item_text[:50]
        if prefix in stripped and stripped.startswith("'" + prefix[:30]):
            # Get the actual full text between the outer quotes
            m = re.match(r"^(\s*')(.*?)(',?)$", line.rstrip('\n'))
            if m:
                ws, inner, suffix = m.group(1), m.group(2), m.group(3)
                new_line = f"{ws}{inner}{SEP}{detail}{suffix}\n"
                updated_lines.append(new_line)
                count += 1
                del remaining[item_text]
                matched = True
                break
    
    if not matched:
        updated_lines.append(line)

content = '\n'.join(updated_lines) if updated_lines[0] else '\n'.join(updated_lines)

# Rejoin properly
with open('client/src/lib/curriculum.ts', 'w') as f:
    f.write('\n'.join(line for line in updated_lines))

print(f"Added detail to {count} items")
print(f"Remaining without detail: {len(remaining)}")
for k in list(remaining.keys())[:10]:
    print(f"  - {k[:70]}")
EOF