// ═══════════════════════════════════════════════════════════════════════════════
// CONTRACTS-6: Contract Modifications, Changes, REAs, and Claims
// ═══════════════════════════════════════════════════════════════════════════════
      {
        id: 'contracts-6',
        title: 'Modifications, REAs & Claims: When Contracts Change',
        duration: '22 min',
        description: 'Master contract modifications, constructive changes, Requests for Equitable Adjustment, and the claims process — the most contentious and costly aspects of contract administration.',
        keyTerms: [
          { term: 'Bilateral Modification', definition: 'A contract change signed by both the contractor and the contracting officer. Used for definitized changes, price adjustments, and scope changes both parties agree to.' },
          { term: 'Unilateral Modification', definition: 'A contract change signed only by the contracting officer, using a contract authority clause (e.g., Changes clause, stop-work order, exercise of option). Contractor may disagree but must perform.' },
          { term: 'Changes Clause', definition: 'FAR 52.243-1 through 52.243-4 — authorizes the CO to direct changes within the general scope of the contract. Contractor must perform the change; has right to an equitable adjustment.' },
          { term: 'Constructive Change', definition: 'A change that is not formally directed but results from government action or inaction that effectively changes the contractor\'s work. Examples: defective specifications, government-caused delays, over-inspection.' },
          { term: 'REA', definition: 'Request for Equitable Adjustment — a contractor\'s formal request for a contract price or schedule adjustment due to a government-directed or constructive change. Precursor to a claim.' },
          { term: 'Claim', definition: 'A written demand by a contractor to the CO for payment of a specific sum, adjustment to contract terms, or other relief — subject to the Contract Disputes Act. Claims over $100K must be certified.' },
          { term: 'Definitization', definition: 'The process of negotiating and finalizing the price and terms of an undefinitized contract action (UCA) — converting a letter contract or other interim vehicle to a fully priced contract.' },
          { term: 'UCA', definition: 'Undefinitized Contract Action — a contract where work begins before price is agreed. Risky for government — contractor has little incentive to control costs before definitization.' },
          { term: 'Contract Disputes Act', definition: '41 U.S.C. § 7101 et seq. — establishes the process for resolving government contract disputes, including CO Final Decisions, ASBCA appeals, and Court of Federal Claims.' },
          { term: 'ASBCA', definition: 'Armed Services Board of Contract Appeals — administrative tribunal that hears contractor appeals of Contracting Officer Final Decisions on contract disputes.' },
        ],
        content: [
          {
            type: 'text',
            heading: 'Why Contract Changes Are Every PM\'s Biggest Financial Risk',
            body: 'The initial contract price is a starting point — not the final cost. On complex defense programs, contract modifications routinely add 20-50% to the original contract value. Every undefinitized UCA, every government-caused delay, every specification change, every constructive change creates entitlement for the contractor to more money. PMs who do not understand modification authority, REA management, and claims risk losing budget discipline entirely. The contractors\' contracts and claims departments are professional — PMs must be equally sophisticated.',
          },
          {
            type: 'table',
            heading: 'Types of Contract Modifications — Know the Difference',
            headers: ['Type', 'Who Signs', 'Authority', 'Common Use', 'Key Risk'],
            rows: [
              ['Bilateral Mod (SF30)', 'CO + Contractor', 'Mutual agreement', 'Definitize changes; price supplements; scope adjustments', 'Scope creep if poorly scoped; waiver of claims if "accord & satisfaction" language added'],
              ['Unilateral Mod — Change Order', 'CO only', 'Changes Clause (FAR 52.243-1)', 'Direct contractor to change work; price to be negotiated after', 'Contractor has 30 days to submit REA; undefinitized cost risk grows over time'],
              ['Unilateral Mod — Admin', 'CO only', 'Administrative necessity', 'Correct errors, change COR, update addresses, issue/modify options', 'Low risk if truly administrative; never use to sneak in scope changes'],
              ['Letter Contract / UCA', 'CO + Contractor', 'FAR 16.603 / DFARS 217.74', 'Begin urgent work before price is agreed; requires definitization schedule', 'Highest risk — contractor bills costs with limited incentive to control; DFARS requires definitization within 180 days'],
            ],
          },
          {
            type: 'text',
            heading: 'The Changes Clause — Your Most Important Tool and Risk',
            body: 'The Changes clause (FAR 52.243-1 for fixed-price supply, 52.243-2 for cost-reimbursable, etc.) is one of the most powerful tools in government contracting. It allows the CO to unilaterally direct changes to the contract\'s technical requirements, delivery schedule, place of performance, or other specified areas — without the contractor\'s consent. The contractor must perform. But the Changes clause also creates the contractor\'s entitlement to an equitable adjustment for any change that increases cost or time. The PM must ensure every directed change is formally documented — verbal direction to "just go do it" is a constructive change waiting to happen.',
          },
          {
            type: 'callout',
            heading: 'Constructive Changes — The Silent Budget Killer',
            body: 'A constructive change is not a formal directive — it is a government action or inaction that effectively changes the contractor\'s work without formal paperwork. Common examples: Government-issued specifications that turn out to be defective (requiring rework); CO over-inspection that goes beyond contract standards; Government delay in furnishing data, GFE, or approvals; Government interference with contractor methods of performance; Informal technical direction from a COR or Government engineer that exceeds their authority. The contractor can pursue an REA or claim for a constructive change years after the work was performed. The best defense is meticulous daily documentation of all government-contractor interactions.',
          },
          {
            type: 'formula',
            heading: 'The REA Process — Timeline and Requirements',
            formula: 'TRIGGER: Government directs change (formal or constructive)\n\nSTEP 1: Contractor submits REA\n  → Must include: Factual basis (what changed), legal entitlement (what clause), quantum (how much $)\n  → No specific time limit — but best practice is 30-60 days after the triggering event\n  → Informal REAs: "We think we\'re entitled" without full cost detail\n  → Formal REAs: Full cost proposal with certified cost/pricing data if >$2M\n\nSTEP 2: Government review\n  → ACO/CO reviews entitlement and quantum\n  → DCAA may audit the REA cost proposal if >$2M\n  → Government requests additional information as needed\n\nSTEP 3: Negotiate bilateral modification\n  → Both parties agree on price and schedule adjustment\n  → Signed bilateral mod definitizes the change\n  → IDEAL OUTCOME: Bilateral mod settles the REA; no claim necessary\n\nIF NEGOTIATIONS FAIL → REA converts to Claim:\n  → Contractor certifies the claim (if >$100K)\n  → CO issues Contracting Officer Final Decision (COFD) within 60 days\n  → Contractor may appeal: ASBCA (administrative) or Court of Federal Claims (judicial)\n  → Interest runs from date of claim submission at Renegotiation Act rate',
            explanation: 'The earlier you can resolve an REA via bilateral modification, the better. Once an REA becomes a claim and enters dispute resolution, costs escalate for both sides and relationships deteriorate. PMs should push for rapid, fair REA resolution — a contractor that knows its REAs will be resolved promptly is less likely to inflate future REAs.',
          },
          {
            type: 'text',
            heading: 'Undefinitized Contract Actions (UCAs) — The Highest-Risk Modification',
            body: 'A UCA (also called a letter contract or undefinitized change order) authorizes a contractor to begin work before the price is agreed. UCAs are necessary for urgent national security situations — but they create serious cost risk. A contractor performing under a UCA has no price ceiling and a weak incentive to control costs: they bill actual costs and know the government will pay them regardless of final negotiated price. DFARS 217.7404 requires definitization within 180 days of initial performance. In practice, many UCAs run for years undefinitized. For PMs, every open UCA is a financial exposure that should be tracked and closed as quickly as possible.',
          },
          {
            type: 'table',
            heading: 'Cardinal Change Doctrine — When a Change Becomes a Breach',
            headers: ['Concept', 'Definition', 'Example', 'Consequence'],
            rows: [
              ['Within-Scope Change', 'Change is within the general scope of the original contract — CO can direct it unilaterally', 'Changing radar frequency range on a radar development contract', 'Contractor must perform; entitled to equitable adjustment'],
              ['Cardinal Change', 'Change so significant it falls outside the general scope — essentially a new contract requirement', 'Changing a radar development contract to also develop a missile guidance system', 'Cannot be directed unilaterally; must be competed separately or bilateral agreement required'],
              ['Change vs. Breach', 'An unauthorized direction that constitutes a cardinal change is a government breach — contractor can terminate for cause', 'CO directs contractor to provide services not contemplated anywhere in the original SOW', 'Contractor entitled to settlement as if for termination for convenience'],
            ],
          },
          {
            type: 'tip',
            heading: 'The PM\'s Best Defense: An Active Change Control Board',
            body: 'Every major program should have a formal Change Control Board (CCB) that reviews, approves, and documents every technical, schedule, or contract change before it is executed. The CCB records: what changed, why, who authorized it, and the estimated cost/schedule impact. Good CCB discipline prevents constructive changes (changes that happen informally), gives the PM visibility into cumulative scope growth, and provides documentation if a contractor\'s REA is disputed. PMs who run informal programs without CCBs routinely lose REA negotiations because they cannot reconstruct what was actually directed.',
          },
          {
            type: 'warning',
            heading: 'Accord & Satisfaction — Read Every Bilateral Mod Carefully',
            body: 'When a contractor signs a bilateral modification that includes "accord and satisfaction" language (or "full and final settlement"), they may be waiving their right to any future claim related to that change. Contractors sometimes sign these under time pressure without fully recognizing the financial waiver. As a PM working with the CO, be aware that modification language matters legally. Conversely, if you want to definitively close out all claims associated with a change, including "full and final settlement" language is appropriate — just ensure both parties understand what they are agreeing to.',
          },
        ],
        quiz: [
          {
            id: 'q1',
            question: 'Which type of contract modification requires signatures from BOTH the contracting officer and the contractor?',
            options: ['Change order', 'Administrative modification', 'Bilateral modification', 'Stop-work order'],
            correct: 2,
            explanation: 'A bilateral modification (Standard Form 30) is executed by both the CO and the contractor, typically reflecting a mutual agreement on scope, price, or schedule changes. Change orders and stop-work orders are unilateral modifications — signed only by the CO using an existing contract authority clause.',
          },
          {
            id: 'q2',
            question: 'A government program manager verbally tells a contractor\'s engineer to "add this new feature while you\'re at it" without a formal contract modification. This most likely creates:',
            options: ['A valid contract change under the Changes clause', 'A constructive change — the contractor may pursue an REA based on government-directed work outside the contract SOW', 'No obligation since it was not in writing', 'An unauthorized commitment by the contractor'],
            correct: 1,
            explanation: 'Verbal direction to perform out-of-scope work without a formal modification is a classic constructive change. The contractor performed work beyond the contract requirements based on government direction. Even without a formal mod, the contractor has entitlement to an equitable adjustment. This is why COR authorities are strictly limited — informal technical direction can bind the government to pay for work without contractual authority.',
          },
          {
            id: 'q3',
            question: 'An Undefinitized Contract Action (UCA) must be definitized within how many days under DFARS 217.7404?',
            options: ['30 days', '90 days', '180 days', '365 days'],
            correct: 2,
            explanation: 'DFARS 217.7404-3 requires UCAs to be definitized within 180 days of issuance of the authorization to proceed, or by the time 50% of the work is completed — whichever comes first. In practice, many UCAs remain undefinitized beyond this requirement. Every day a UCA is undefinitized, the government faces increasing cost risk because the contractor is billing actual costs with no negotiated price ceiling.',
          },
          {
            id: 'q4',
            question: 'A contractor submits an REA that grows into a formal claim of $2.5M. For the claim to be valid, it must be:',
            options: ['Submitted within 30 days of the change', 'Certified by a senior company official and submitted as a written demand to the CO', 'Approved by DCAA before submission', 'Accompanied by a technical evaluation from DCMA'],
            correct: 1,
            explanation: 'Under the Contract Disputes Act (41 U.S.C. § 7103), claims exceeding $100K must be certified by an authorized contractor representative that the claim is made in good faith, supporting data are accurate and complete to the best of their knowledge, and the amount requested accurately reflects the contract adjustment believed to be due. False certification can expose the contractor to criminal liability under the False Claims Act.',
          },
          {
            id: 'q5',
            question: 'A "cardinal change" is significant because:',
            options: ['It requires a 30-day waiting period before performance', 'It falls outside the general scope of the contract and cannot be directed unilaterally — it may constitute a breach', 'It always requires Congressional approval', 'It must be competed under full and open competition'],
            correct: 1,
            explanation: 'The cardinal change doctrine (developed through case law at the ASBCA and Court of Federal Claims) holds that changes so substantial they alter the nature of the bargained-for contract cannot be directed unilaterally under the Changes clause. Doing so constitutes a government breach, and the contractor is entitled to breach remedies. For PMs, this means very large scope additions should be scrutinized for cardinal change risk before direction is issued.',
          },
          {
            id: 'q6',
            question: 'A Contracting Officer Final Decision (COFD) in response to a contractor claim must be issued within:',
            options: ['30 days of the claim', '60 days of the claim (or reasonable time with notification for complex claims)', '180 days', 'There is no time requirement'],
            correct: 1,
            explanation: 'The Contract Disputes Act requires the CO to issue a Final Decision within 60 days of a certified claim, or within a reasonable time for more complex claims — provided the CO notifies the contractor of the anticipated decision date. If the CO fails to issue a COFD, the contractor may treat the inaction as a denial and appeal directly to the ASBCA or Court of Federal Claims (deemed denial).',
          },
          {
            id: 'q7',
            question: 'Which of the following is an example of a constructive change based on defective government specifications?',
            options: ['The CO directs a formal change to the system\'s performance requirements', 'Government-provided technical specifications contain errors that cause the contractor to perform excessive rework to meet the actual requirement', 'The contractor voluntarily redesigns the system to improve performance', 'The CO exercises an option on the contract'],
            correct: 1,
            explanation: 'Defective government specifications are one of the most common sources of constructive changes. When the government provides faulty specs that the contractor relies on — only to find they are incorrect or impossible to meet — the extra work required to correct the problem is a constructive change entitling the contractor to an equitable adjustment. The government warrants the accuracy of specifications it provides (the "Spearin Doctrine," 248 U.S. 132 (1918)).',
          },
          {
            id: 'q8',
            question: 'A bilateral modification that includes "full and final settlement" language regarding all claims related to a change means:',
            options: ['The contractor retains the right to pursue additional claims for hidden costs', 'The contractor waives their right to future claims arising from that change — an accord and satisfaction', 'DCAA must approve the settlement before it is final', 'The modification automatically triggers a DCMA review'],
            correct: 1,
            explanation: '"Accord and satisfaction" in a bilateral mod means both parties agree the modification fully resolves all claims arising from the specified change. Once signed, the contractor generally cannot pursue additional claims for that change. This is a powerful tool for closing out changes cleanly — but contractors sometimes sign without fully understanding the financial waiver implications.',
          },
          {
            id: 'q9',
            question: 'The ASBCA (Armed Services Board of Contract Appeals) has jurisdiction over:',
            options: ['Pre-award bid protests by losing offerors', 'Contractor appeals of Contracting Officer Final Decisions (COFDs) on contract disputes', 'DCAA audit disputes between contractors and auditors', 'Congressional notification of Nunn-McCurdy breaches'],
            correct: 1,
            explanation: 'The ASBCA (and its civilian counterpart, the CBCA) hears contractor appeals of CO Final Decisions under the Contract Disputes Act. It is an administrative tribunal (not a federal court), but its decisions can be appealed to the Court of Appeals for the Federal Circuit. The alternative forum is the U.S. Court of Federal Claims, a judicial (Article III) court.',
          },
          {
            id: 'q10',
            question: 'A Change Control Board (CCB) on a major defense program primarily serves to:',
            options: ['Review and approve DCAA audit findings before they are released', 'Document, review, and approve all technical and contractual changes before execution — preventing constructive changes and scope creep', 'Authorize program managers to exceed budget without congressional notification', 'Approve new hire requests for the program office'],
            correct: 1,
            explanation: 'A CCB provides the formal process for evaluating and approving changes to the baseline — technical, schedule, and contractual. Every proposed change is evaluated for cost/schedule impact before it is directed. This prevents informal, undocumented changes (constructive changes) and gives the PM a documented record of all directed changes — essential for defending against REAs that claim the government directed more work than the formal record shows.',
          },
          {
            id: 'q11',
            type: 'drag_order',
            question: 'Place the REA-to-Claim process in the correct sequence:',
            options: [],
            correct: 0,
            explanation: 'The process flows: triggering change → contractor submits REA → government review/DCAA audit of cost proposal → negotiation → bilateral mod (ideal resolution). If negotiation fails, the REA becomes a certified claim → CO issues Final Decision → contractor may appeal to ASBCA or Court of Federal Claims. Each step that advances past bilateral mod resolution increases cost and time for both parties.',
            orderedItems: [
              'Government directs change (formal or constructive)',
              'Contractor submits REA with entitlement and cost proposal',
              'DCAA audits REA cost proposal (if >$2M)',
              'CO and contractor negotiate equitable adjustment',
              'Bilateral modification definitizes the change (ideal outcome)',
              'If failed: REA converts to certified Claim; CO issues Final Decision',
            ],
          },
          {
            id: 'q12',
            type: 'drag_match',
            question: 'Match each modification or change concept to its correct definition:',
            options: [],
            correct: 0,
            explanation: 'These concepts form the vocabulary of contract changes. Bilateral mods require consent; unilateral mods do not. Constructive changes happen informally. UCAs are open-ended cost risks. Cardinal changes exceed what can be directed unilaterally. Understanding each distinction allows PMs to manage scope, cost, and legal exposure effectively.',
            pairs: [
              { left: 'Bilateral Modification', right: 'Requires signatures from both CO and contractor' },
              { left: 'Constructive Change', right: 'Informal government direction or inaction that effectively changes the work' },
              { left: 'UCA (Letter Contract)', right: 'Work begins before price is agreed; must be definitized within 180 days' },
              { left: 'Cardinal Change', right: 'Change outside original scope; cannot be directed unilaterally; may be a breach' },
            ],
          },
        ],
      },

// ═══════════════════════════════════════════════════════════════════════════════
// FOUNDATIONS-3: ACAT Levels, Oversight, and Program Tailoring
// ═══════════════════════════════════════════════════════════════════════════════
      {
        id: 'foundations-3',
        title: 'ACAT Levels: How the DoD Categorizes Your Program',
        duration: '18 min',
        description: 'Master ACAT levels, milestone decision authority, tailoring, and how program categorization drives oversight, reporting, and your day-to-day responsibilities as a PM.',
        keyTerms: [
          { term: 'ACAT', definition: 'Acquisition Category — a classification system that determines the level of oversight, reporting, and milestone decision authority for a DoD acquisition program. Higher ACAT = more oversight.' },
          { term: 'ACAT I', definition: 'Major Defense Acquisition Program — total cost > $480M (RDT&E) or $2.79B (procurement). MDA is USD(A&S) or a designated Service Acquisition Executive (SAE). Highest oversight.' },
          { term: 'ACAT II', definition: 'Major System — total cost > $185M (RDT&E) or $835M (procurement). MDA is the DoD Component Acquisition Executive (CAE). Significant but less oversight than ACAT I.' },
          { term: 'ACAT III', definition: 'Below ACAT I/II thresholds. MDA is designated by the CAE, typically a Program Executive Officer (PEO) or head of contracting activity. Streamlined oversight.' },
          { term: 'ACAT IV', definition: 'Services and non-major acquisitions managed below ACAT III threshold. Component manages with minimal centralized oversight.' },
          { term: 'MDA', definition: 'Milestone Decision Authority — the individual with authority to approve milestones, authorize program entry into lifecycle phases, and certify programs. Varies by ACAT level.' },
          { term: 'SAE', definition: 'Service Acquisition Executive — the senior official responsible for acquisition programs within an Armed Service (ASA(ALT) for Army, ASN(RDA) for Navy/USMC, SAF/AQ for Air Force/Space Force).' },
          { term: 'Tailoring', definition: 'The process of adjusting DoDI 5000.02 requirements to match the program\'s complexity, acquisition pathway, risk, and urgency. Not all programs need all standard requirements.' },
          { term: 'AAF', definition: 'Adaptive Acquisition Framework — DoDI 5000.02\'s six acquisition pathways, allowing programs to select the pathway best suited to their type of acquisition.' },
          { term: 'MDAP', definition: 'Major Defense Acquisition Program — an ACAT I program. Subject to full statutory reporting to Congress (SAR, unit cost reporting) and CAPE independent cost estimates at each milestone.' },
        ],
        content: [
          {
            type: 'text',
            heading: 'Why ACAT Level Determines Your Entire Program Experience',
            body: 'The first question asked about any new DoD acquisition is: what ACAT is this program? The answer determines who approves your milestones, how many oversight reviews you will conduct, whether you need an independent cost estimate, whether you must report to Congress, and how much staff support you will have. An ACAT I program like the F-35 involves USD(A&S) as the MDA, mandatory SAR reports to Congress, CAPE independent cost estimates, and DoD-level reviews at every milestone. An ACAT III program may be approved by a PEO with minimal external oversight. Understanding ACAT levels is the starting point for understanding any DoD program\'s regulatory environment.',
          },
          {
            type: 'table',
            heading: 'ACAT Levels — Thresholds, MDA, and Key Requirements',
            headers: ['ACAT', 'Cost Threshold (2024)', 'MDA', 'Key Requirements', 'Reporting'],
            rows: [
              ['ACAT ID', 'RDT&E > $480M or Procurement > $2.79B; OR designated by USD(A&S)', 'USD(A&S) or designated SAE', 'Full DoDI 5000 compliance; ICE required; full documentation', 'SAR to Congress; unit cost reporting; CAPE ICE'],
              ['ACAT IC', 'Same thresholds as ACAT ID', 'Component Acquisition Executive (CAE) / SAE', 'Same as ACAT ID minus OSD-level milestone approval', 'SAR; CAPE ICE optional but often requested'],
              ['ACAT II', 'RDT&E > $185M or Procurement > $835M', 'CAE (ASA(ALT), ASN(RDA), SAF/AQ)', 'Component-level ICE; DoDI 5000 compliance with tailoring', 'Component-level reporting; no mandatory SAR'],
              ['ACAT III', 'Below ACAT I/II; designated by CAE', 'PEO or designated official', 'Significant tailoring available; streamlined documentation', 'Program office reporting only'],
              ['ACAT IV', 'Non-major services/acquisitions', 'Head of contracting activity', 'Minimum oversight; acquisition plan required', 'Internal only'],
            ],
          },
          {
            type: 'text',
            heading: 'The Adaptive Acquisition Framework — Six Pathways',
            body: 'DoDI 5000.02 (updated in 2020) introduced the Adaptive Acquisition Framework (AAF), replacing the previous "one-size-fits-all" linear acquisition model with six distinct pathways. Each pathway is tailored to a specific type of acquisition: (1) Major Capability Acquisition (MCA) — the traditional ACAT process for large, complex defense systems; (2) Middle Tier of Acquisition (MTA) — Rapid Prototyping (2 years) or Rapid Fielding (5 years); (3) Software Acquisition — for software-intensive systems using Agile/DevSecOps; (4) Defense Business Systems (DBS) — for ERP and business IT systems; (5) Acquisition of Services — for services contracts managed under the service acquisition framework; (6) Urgent Capability Acquisition — for combat-emergent needs addressable within 2 years.',
          },
          {
            type: 'table',
            heading: 'AAF Pathway Selection Guide',
            headers: ['Pathway', 'Best For', 'Timeline', 'Key Advantage'],
            rows: [
              ['Major Capability Acquisition (MCA)', 'Large, complex systems requiring full R&D lifecycle (aircraft, ships, satellites)', '10-20+ years', 'Full oversight and documentation — appropriate for highest-risk, highest-cost programs'],
              ['Middle Tier — Rapid Prototyping', 'Technology demonstrations; filling known capability gaps quickly', '≤ 2 years to field', 'Skip traditional milestones; prototype and learn fast'],
              ['Middle Tier — Rapid Fielding', 'Mature technology ready to field with minor modification', '≤ 5 years to field', 'Streamlined acquisition; use existing systems/platforms'],
              ['Software Acquisition', 'Software-intensive systems; cloud apps; command and control IT', 'Continuous delivery cycles', 'Agile/DevSecOps; iterative delivery; avoid "big bang" software programs'],
              ['Defense Business Systems', 'ERP, finance, HR, logistics IT systems', 'Per commercial release cycle', 'Use commercial software best practices; avoid military customization'],
              ['Urgent Capability Acquisition', 'Combat-emergent gaps; urgent warfighter needs', '≤ 2 years', 'Highest streamlining; near-direct fielding from combatant command request'],
            ],
          },
          {
            type: 'callout',
            heading: 'ACAT Determination Is Not Static — Programs Get Re-Categorized',
            body: 'Programs can be re-categorized upward if cost growth triggers higher ACAT thresholds — which means more oversight, more reporting, and a new MDA. An ACAT II program that grows to ACAT I cost levels gets re-designated, and the PM suddenly must comply with full ACAT I requirements retroactively. This is another reason aggressive cost management is not just financial discipline — it is also a program management imperative to avoid triggering additional oversight burdens.',
          },
          {
            type: 'text',
            heading: 'Selected Acquisition Report (SAR) — The ACAT I Report to Congress',
            body: 'For ACAT I programs (MDAPs), the PM must produce a Selected Acquisition Report (SAR) annually — or whenever a Nunn-McCurdy breach or other significant change occurs. The SAR is submitted to Congress and covers: current program description, total program cost (including all variants), cost and schedule changes from original baseline, current schedule, and performance status. The SAR is a legal disclosure document — PMs must ensure all data is accurate. False or misleading SARs can trigger Congressional investigations. For an experienced PM, the SAR is also a professional document that reflects directly on your program\'s credibility and your ability to manage to a baseline.',
          },
          {
            type: 'formula',
            heading: 'Key ACAT I Statutory Requirements — What Congress Requires',
            formula: 'MANDATORY FOR ACAT I (MDAP) PROGRAMS:\n\n1. Selected Acquisition Report (SAR)\n   → Annual submission to Congress\n   → Unit cost growth > 15% (significant breach) triggers special SAR\n\n2. Independent Cost Estimate (ICE)\n   → Required at each Milestone (A, B, C)\n   → CAPE prepares for ACAT ID; Service cost center for ACAT IC\n\n3. Nunn-McCurdy Unit Cost Reporting\n   → Significant breach: 15% cost growth over baseline\n   → Critical breach: 25% cost growth over baseline → Congressional notification + USD(A&S) certification\n\n4. Acquisition Program Baseline (APB)\n   → Formally documents cost, schedule, and performance objectives\n   → Breaches of APB thresholds trigger reporting and review\n\n5. Test and Evaluation Master Plan (TEMP)\n   → Documents all DT&E, OT&E, and LFT&E requirements\n   → Must be approved by DOT&E for major programs',
            explanation: 'These requirements are statutory — they come from law (USC Title 10), not just DoD policy. That means Congress mandated them, and they cannot be tailored away regardless of what the PM or MDA prefers. As an ACAT I PM, these are non-negotiable obligations.',
          },
          {
            type: 'tip',
            heading: 'Tailoring — Use It, Don\'t Abuse It',
            body: 'Tailoring under DoDI 5000.02 allows PMs to adjust documentation, review, and reporting requirements based on program risk, complexity, and pathway. A small ACAT III program does not need a 200-page Acquisition Strategy or a full EVMS — tailoring allows appropriate scaling. However, tailoring is a two-way street: the MDA can also impose additional requirements if the program needs more oversight. The best tailoring approach is to clearly justify every decision to omit or reduce a requirement — not simply to skip paperwork but to demonstrate the program has equivalent risk management in place.',
          },
        ],
        quiz: [
          {
            id: 'q1',
            question: 'An ACAT I program (MDAP) requires which of the following that ACAT III programs do not?',
            options: ['A written acquisition strategy', 'A Selected Acquisition Report (SAR) submitted to Congress and an Independent Cost Estimate at each milestone', 'A Performance Work Statement', 'A contract administration plan'],
            correct: 1,
            explanation: 'ACAT I programs are MDAPs subject to statutory reporting requirements including annual SARs to Congress, CAPE independent cost estimates at each milestone, and Nunn-McCurdy unit cost reporting. ACAT III programs require an acquisition strategy and various documents, but are not subject to mandatory Congressional reporting via SAR.',
          },
          {
            id: 'q2',
            question: 'The current ACAT I threshold for Research, Development, Test and Evaluation (RDT&E) is approximately:',
            options: ['$100M', '$185M', '$480M', '$2.79B'],
            correct: 2,
            explanation: 'Programs with RDT&E costs exceeding approximately $480M (or procurement costs exceeding $2.79B) are classified ACAT I. These thresholds are adjusted periodically for inflation. Programs below $185M RDT&E / $835M procurement are typically ACAT III.',
          },
          {
            id: 'q3',
            question: 'Under the Adaptive Acquisition Framework, the "Middle Tier — Rapid Prototyping" pathway is designed for programs that can:',
            options: ['Take 20 years to deliver a full production system', 'Field a prototype or demonstration within 2 years, leveraging existing technology', 'Deliver software via continuous Agile sprints', 'Acquire commercial off-the-shelf services directly'],
            correct: 1,
            explanation: 'Rapid Prototyping (AAF Middle Tier) allows programs to field a prototype or proof of concept within 2 years, bypassing traditional Milestone A-B-C review requirements. It is intended for programs using mature technology that can be demonstrated quickly — not for programs requiring extensive R&D.',
          },
          {
            id: 'q4',
            question: 'If an ACAT II program\'s costs grow and exceed ACAT I thresholds, what happens?',
            options: ['The program is automatically cancelled', 'The program is re-designated as ACAT I, triggering additional oversight requirements, SAR reporting, and a new MDA', 'The program continues under ACAT II oversight regardless of cost growth', 'The PM must request a waiver from Congress'],
            correct: 1,
            explanation: 'ACAT categorization follows cost — if a program grows beyond the ACAT II threshold into ACAT I territory, it must be re-designated ACAT I. This brings additional requirements: the MDA shifts to USD(A&S) or SAE, SAR reporting begins, CAPE ICE is required, and Nunn-McCurdy cost reporting applies. This is why PM cost management is both a financial and an oversight discipline.',
          },
          {
            id: 'q5',
            question: 'Tailoring under DoDI 5000.02 allows a PM to:',
            options: ['Eliminate all oversight requirements for expedited programs', 'Adjust documentation, review, and reporting requirements based on program risk and pathway — with MDA approval', 'Override Congressional reporting requirements for classified programs', 'Skip the Acquisition Program Baseline for rapid fielding programs'],
            correct: 1,
            explanation: 'Tailoring is a policy mechanism — it requires MDA approval and must be documented in the Acquisition Strategy. Statutory requirements (SAR, Nunn-McCurdy, ICE for ACAT I) cannot be tailored away. Tailoring adjusts DoD policy requirements (specific documents, review formats, approval levels) to be appropriately scaled to the program\'s complexity and risk.',
          },
          {
            id: 'q6',
            question: 'The Milestone Decision Authority (MDA) for an ACAT ID program is:',
            options: ['The Program Manager', 'The Program Executive Officer (PEO)', 'USD(A&S) or designated Service Acquisition Executive', 'The Secretary of Defense'],
            correct: 2,
            explanation: 'ACAT ID MDAs are USD(A&S) or a designated Service Acquisition Executive (SAE) — the most senior acquisition officials in their respective Service. ACAT IC MDAs are also the SAE. For ACAT II, the MDA is typically the CAE. For ACAT III, it may be the PEO. The MDA is the one person who can approve milestone entry — the PM\'s most critical stakeholder.',
          },
          {
            id: 'q7',
            question: 'An Acquisition Program Baseline (APB) documents which three key program parameters?',
            options: ['Contract type, vendor selection, and delivery location', 'Cost objectives (threshold and objective), schedule, and performance (key performance parameters)', 'Funding levels, test events, and contractor team', 'Congressional appropriations, FYDP profile, and POM submission'],
            correct: 1,
            explanation: 'The APB establishes the program\'s "triple constraint" baseline: cost (threshold and objective values), schedule (key milestone dates), and performance (Key Performance Parameters from the capabilities document). Breaches of APB threshold values trigger reporting and potentially MDA review. The APB is the official record of what the program promised to deliver at what cost and schedule.',
          },
          {
            id: 'q8',
            question: 'The "Software Acquisition" pathway under the AAF is specifically designed for:',
            options: ['Purchasing commercial off-the-shelf software licenses', 'Software-intensive systems using continuous delivery, Agile development, and DevSecOps practices', 'Programs that use software as a minor component of a hardware-dominant system', 'Business system acquisitions below $185M'],
            correct: 1,
            explanation: 'The Software Acquisition pathway (DoDI 5000.87) enables Agile/DevSecOps continuous delivery for software-intensive programs — replacing the traditional "plan everything upfront, deliver years later" model. It is intended for programs where software is the primary deliverable and iterative development cycles are appropriate. It is distinct from Defense Business Systems, which handles ERP and administrative IT.',
          },
          {
            id: 'q9',
            question: 'A Selected Acquisition Report (SAR) is submitted to Congress:',
            options: ['Monthly during active program phases', 'Annually, and additionally whenever a Nunn-McCurdy breach or significant baseline change occurs', 'Only when a program is cancelled', 'Only at each major milestone decision'],
            correct: 1,
            explanation: 'SARs are annual reports to Congress covering ACAT I program cost, schedule, and performance status. Special SARs are required when a Nunn-McCurdy breach occurs (significant 15% or critical 25% unit cost growth). They represent one of the primary mechanisms through which Congress exercises oversight over major defense programs.',
          },
          {
            id: 'q10',
            question: 'What distinguishes an "Urgent Capability Acquisition" pathway program from a standard ACAT program?',
            options: ['It requires more oversight due to its urgency', 'It allows fielding a capability within 2 years through streamlined approvals, typically driven by combatant command urgent needs', 'It is only available to classified programs', 'It eliminates all contractor competition requirements'],
            correct: 1,
            explanation: 'The Urgent Capability Acquisition pathway (governed by DoDI 5000.02 Enclosure 8) enables rapid response to urgent warfighter needs — typically within 2 years. It uses streamlined milestone approvals, expedited contracting, and flexible oversight tailored to the urgency. It does not eliminate competition where time allows, but allows use of other-than-full-and-open competition procedures under FAR 6.302.',
          },
          {
            id: 'q11',
            type: 'drag_match',
            question: 'Match each AAF pathway to the type of acquisition it is designed for:',
            options: [],
            correct: 0,
            explanation: 'Each AAF pathway is designed for a specific acquisition type and risk profile. Matching the pathway to the program type is the first decision a PM makes — choosing the wrong pathway creates unnecessary overhead (e.g., applying full MCA process to a software program) or insufficient oversight (e.g., using Rapid Fielding for an immature technology).',
            pairs: [
              { left: 'Major Capability Acquisition', right: 'Large complex defense systems: aircraft, ships, satellites' },
              { left: 'Middle Tier — Rapid Prototyping', right: 'Field a prototype within 2 years using mature technology' },
              { left: 'Software Acquisition', right: 'Software-intensive systems using Agile/DevSecOps continuous delivery' },
              { left: 'Urgent Capability Acquisition', right: 'Combat-emergent warfighter need requiring capability within 2 years' },
            ],
          },
          {
            id: 'q12',
            type: 'drag_order',
            question: 'Place these ACAT I program milestone events in the correct lifecycle order:',
            options: [],
            correct: 0,
            explanation: 'The ACAT I lifecycle flows: Milestone A approves entry into Technology Maturation and Risk Reduction (TMRR) → Milestone B approves entry into Engineering and Manufacturing Development (EMD) → Milestone C approves entry into Production and Deployment → Full-Rate Production (FRP) Decision authorizes full production. Each milestone is preceded by a Defense Acquisition Board (DAB) review at the OSD level for ACAT ID programs.',
            orderedItems: [
              'Milestone A — Entry into Technology Maturation & Risk Reduction (TMRR)',
              'Milestone B — Entry into Engineering & Manufacturing Development (EMD)',
              'Milestone C — Entry into Production & Deployment (Low-Rate Initial Production authorized)',
              'Full-Rate Production (FRP) Decision — After IOT&E completion',
            ],
          },
        ],
      },

// ═══════════════════════════════════════════════════════════════════════════════
// FOUNDATIONS-4: Other Transaction Authority, FAR Part 12, and Streamlined Paths
// ═══════════════════════════════════════════════════════════════════════════════
      {
        id: 'foundations-4',
        title: 'OTAs, FAR Part 12 & Streamlined Acquisition Authorities',
        duration: '18 min',
        description: 'Master Other Transaction Authority, commercial item acquisition under FAR Part 12, Simplified Acquisition Procedures, and the emerging tools that let DoD move at the speed of relevance.',
        keyTerms: [
          { term: 'OTA', definition: 'Other Transaction Authority — statutory authority allowing DoD to enter agreements (not contracts) for prototype projects and follow-on production outside FAR/DFARS requirements.' },
          { term: 'Other Transaction Agreement', definition: 'An agreement (not a procurement contract) executed under OTA authority. Not subject to FAR, DFARS, CAS, or most standard acquisition regulations.' },
          { term: 'FAR Part 12', definition: 'Acquisition of Commercial Products and Commercial Services — streamlined procedures for buying items available in the commercial marketplace, with reduced regulatory burden.' },
          { term: 'Commercial Item', definition: 'An item sold or offered in the commercial marketplace for non-government purposes. FAR Part 12 allows acquisition with fewer regulations and no certified cost or pricing data requirement.' },
          { term: 'SAP', definition: 'Simplified Acquisition Procedures — streamlined procurement process for purchases below the SAT ($350K). Faster, less documentation, but still requires competition where practical.' },
          { term: 'SAT', definition: 'Simplified Acquisition Threshold — $350K (effective October 1, 2025). Acquisitions below this threshold use SAP. Between SAT and $750K there are additional micro-purchase/simplified procedures.' },
          { term: 'Micro-Purchase', definition: 'Purchases at or below $15K. May be made by any government employee with a purchase card without competition requirement (FAR Part 13.2).' },
          { term: 'Sole Source', definition: 'Award without competition. Requires justification under FAR 6.302 — valid reasons include: only one responsible source, urgency, national security, follow-on R&D.' },
          { term: 'COTS', definition: 'Commercial Off-The-Shelf — products sold or used commercially without modification. COTS acquisition is the fastest, cheapest path but requires active market research.' },
          { term: '10 USC 4022', definition: 'The primary statutory authority for DoD prototype OTAs and follow-on production OTAs. Allows non-traditional defense contractors to participate without the FAR compliance burden.' },
        ],
        content: [
          {
            type: 'text',
            heading: 'The Regulatory Burden Problem — Why Streamlined Paths Exist',
            body: 'The FAR and DFARS were designed for accountability and competition — but they create a compliance burden that some commercial technology companies refuse to accept. Google, Amazon, and many AI/tech firms will not participate in traditional DoD contracting because CAS compliance, DFARS business systems requirements, and certified cost or pricing data requirements add millions in overhead costs and years in lead time. DoD created streamlined paths — OTAs, FAR Part 12, SAP — to access commercial innovation that would otherwise avoid the defense market. As a PM, knowing when to use these paths is as important as knowing how to run a traditional acquisition.',
          },
          {
            type: 'table',
            heading: 'Acquisition Paths Compared — Regulatory Burden vs. Speed',
            headers: ['Path', 'Regulatory Burden', 'Timeline', 'Best For', 'Key Limitation'],
            rows: [
              ['Traditional FAR/DFARS Contract', 'Full FAR/DFARS/CAS compliance', '12-36+ months', 'Complex development; cost-reimbursable R&D; traditional defense programs', 'Slow; excludes many commercial firms'],
              ['FAR Part 12 Commercial', 'Reduced — no CAS, no certified cost data', '6-18 months', 'Products/services available commercially without substantial modification', 'Item must be genuinely commercial'],
              ['OTA Prototype', 'No FAR/DFARS/CAS', '3-12 months', 'Innovative prototypes; non-traditional contractors; technology demonstration', 'Non-competitive follow-on must still meet criteria'],
              ['OTA Production (follow-on)', 'No FAR/DFARS', '1-6 months if directly follows prototype', 'Production of successfully demonstrated OTA prototype', 'Requires successful prototype; scale limits apply'],
              ['Simplified Acquisition Procedures', 'Minimal', 'Days to weeks', 'Purchases < $350K; immediate needs', '$350K ceiling; cannot be used to circumvent competition for larger requirements'],
              ['Micro-Purchase', 'None', 'Hours', 'Purchases < $10K; credit card', '$10K ceiling; no strategic use'],
            ],
          },
          {
            type: 'text',
            heading: 'Other Transaction Authority — The Most Powerful Tool You\'re Not Using Enough',
            body: 'OTA was originally authorized in 1958 for NASA (10 USC 4001) and expanded dramatically for DoD prototyping in the 2010s. Under 10 USC 4022, DoD can enter prototype OTAs and — critically — non-competitively award follow-on production contracts to the OTA performer if the prototype is successfully demonstrated. This is a major advantage: a company can win prototype work through OTA, demonstrate success, and then convert directly to production without re-competing. For DoD, OTA allows engagement with commercial tech firms, startups, and nontraditional contractors who refuse FAR-regulated contracts. OTA agreements can include flexible payment terms, IP arrangements, and milestone-based payments that are impossible under FAR.',
          },
          {
            type: 'callout',
            heading: 'OTA Safeguards — What You Can\'t Do',
            body: 'OTA is powerful but not unlimited. Key restrictions: (1) Prototype OTAs must include at least one "nontraditional defense contractor" (a company that has not received DoD contracts over $1M in the past year subject to full CAS compliance) OR significant government cost-share (one-third of total project cost). (2) The prototype must be for a "prototype project" — not production of a fielded system. (3) Follow-on production OTAs require a successful demonstration of the prototype. (4) Congress must be notified of OTAs over $500M. (5) OTAs over $250M generally require competitive processes. There is significant congressional scrutiny of OTA misuse — using OTA to avoid competition for production work that should be competitively bid.',
          },
          {
            type: 'formula',
            heading: 'FAR Part 12 Commercial Item Determination — The Test',
            formula: 'FAR 2.101 defines "commercial product" — meets ANY of these:\n\n1. Sold/offered for sale in the commercial marketplace in the past 3 years\n2. Sold/offered in modified form (modifications customary to commercial market)\n3. An item that evolved from a commercial item through advances in technology\n4. Any item described in (1)-(3) for which modifications are described in (2)\n\nCOMMERCIAL SERVICES test (FAR 2.101):\n→ Offered and sold competitively to the general public\n→ Established catalog or market prices for specific tasks performed\n→ Not developed exclusively for government use\n\nIF COMMERCIAL → FAR Part 12 applies:\n  → No certified cost or pricing data (no TINA)\n  → No CAS\n  → Reduced DFARS clauses (FAR 52.212-4 and 52.212-5 replace dozens of clauses)\n  → Use of commercial warranty and terms\n  → No requirement for government-unique accounting\n  → Streamlined source selection using simplified procedures',
            explanation: 'The commercial item determination is made by the contracting officer, but the PM drives the market research that supports it. Document your market research thoroughly — a challenged commercial item determination can unravel an entire acquisition strategy post-award.',
          },
          {
            type: 'table',
            heading: 'Sole Source Justifications Under FAR 6.302 — When Competition Is Not Required',
            headers: ['Exception', 'FAR Cite', 'Example', 'Key Documentation Required'],
            rows: [
              ['Only one responsible source', 'FAR 6.302-1', 'Spare parts from OEM only; unique IP holder', 'J&A documenting why only one source can satisfy requirement'],
              ['Unusual and compelling urgency', 'FAR 6.302-2', 'Time-critical mission need; emergency repair', 'J&A with timeline; limited period; must compete ASAP'],
              ['Industrial mobilization; engineering development', 'FAR 6.302-3', 'Maintaining defense industrial base capability', 'D&F with SecDef or component secretary approval'],
              ['International agreement', 'FAR 6.302-4', 'NATO standardization agreement requires specific vendor', 'Reference to international agreement'],
              ['Authorized or required by statute', 'FAR 6.302-5', 'Small Business set-asides; 8(a) direct awards', 'Documentation of statutory authority'],
              ['National security', 'FAR 6.302-6', 'Classified programs; ITAR restrictions', 'National security D&F'],
            ],
          },
          {
            type: 'text',
            heading: 'Simplified Acquisition Procedures — Speed and Flexibility for Small Buys',
            body: 'For purchases below $350K, FAR Part 13 allows significantly streamlined procedures. Competition is still encouraged — generally three quotes are sufficient — but the complex evaluation, documentation, and review requirements of FAR Part 15 do not apply. Below $15K (micro-purchase threshold), Government Purchase Card (GPC) holders can buy without any competition requirement. For PMs managing programs with many small supporting contracts, understanding SAP allows faster decisions without compromising legal compliance. However, SAP cannot be used to intentionally break up larger requirements to stay below the threshold (a practice called "split purchasing" — a federal violation).',
          },
          {
            type: 'warning',
            heading: 'OTA Abuse — A Growing Congressional Concern',
            body: 'OTA use has grown dramatically — from $3.4B in FY2017 to over $23B in recent years. Congress has flagged concerns about OTA being used to circumvent competition requirements for production work that should be competitively bid, and about follow-on production OTAs being used well beyond the demonstrated prototype scope. PMs must ensure OTAs are used appropriately: for genuine prototypes, with nontraditional contractor participation, and for production only when the prototype was successfully demonstrated. An OTA that looks like a production contract without competition will face Congressional scrutiny and potential investigation.',
          },
          {
            type: 'tip',
            heading: 'Practical OTA Uses for Today\'s PM',
            body: 'Modern defense PMs use OTAs for: AI/ML capability demonstrations with Silicon Valley firms; cybersecurity prototype testing with startups; rapid software prototyping with nontraditional vendors; cloud platform demonstrations. The key is ensuring your OTA is genuinely a prototype — a learning/demonstration activity — not production by another name. Work closely with your legal and contracting teams. The most common OTA mistake is treating it as a shortcut to sole-source production rather than a genuine innovation tool.',
          },
        ],
        quiz: [
          {
            id: 'q1',
            question: 'What makes OTA (Other Transaction Authority) attractive to non-traditional defense contractors like tech startups?',
            options: ['OTA provides larger contracts than FAR-based contracts', 'OTA agreements are not subject to FAR, DFARS, or CAS requirements — eliminating compliance costs that deter commercial firms', 'OTA guarantees sole-source follow-on production', 'OTA eliminates all intellectual property protections for the government'],
            correct: 1,
            explanation: 'The primary appeal of OTA for nontraditional contractors is freedom from FAR/DFARS/CAS compliance — the accounting, reporting, and audit requirements that add significant overhead costs and complexity. Companies like commercial AI firms, cloud providers, and defense tech startups often refuse traditional DoD contracts specifically because of this compliance burden. OTA removes those barriers.',
          },
          {
            id: 'q2',
            question: 'Under 10 USC 4022, a follow-on production OTA (without competition) is permitted when:',
            options: ['The program manager approves it', 'The prototype project was competitively awarded and successfully demonstrated', 'Congress has not objected within 30 days', 'The original OTA was below $100M'],
            correct: 1,
            explanation: 'A key benefit of prototype OTAs is the ability to award follow-on production to the same performer without competition — IF the prototype was competitively awarded (or met the nontraditional contractor requirement) AND was successfully demonstrated. This production must directly follow from the demonstrated prototype; using it to award unrelated production work is OTA misuse.',
          },
          {
            id: 'q3',
            question: 'A product qualifies as "commercial" under FAR Part 12 when:',
            options: ['It was developed specifically for DoD', 'It has been sold or offered for sale in the commercial marketplace, or evolved from such an item through advances in technology', 'It costs less than the simplified acquisition threshold', 'The contractor certifies it does not require unique modifications'],
            correct: 1,
            explanation: 'FAR 2.101 defines commercial products broadly — sold in the commercial marketplace, offered with customary modifications, or evolved from commercial items. The CO makes the determination based on market research. Commercial item status eliminates CAS, certified cost or pricing data (TINA), and many DFARS clauses — dramatically reducing contractor compliance burden.',
          },
          {
            id: 'q4',
            question: 'The simplified acquisition threshold (SAT) is currently:',
            options: ['$10,000', '$50,000', '$150,000', '$350,000'],
            correct: 3,
            explanation: 'The SAT is $350,000, effective October 1, 2025 per FAR 2.101 (updated by the Federal Acquisition Circular FAC 2025-07). Acquisitions below the SAT use simplified acquisition procedures (FAR Part 13). The micro-purchase threshold (no competition required) is $15,000. The SAT is adjusted periodically for inflation and certain exceptions apply (e.g., commercial items, construction).',
          },
          {
            id: 'q5',
            question: '"Split purchasing" — intentionally breaking a $500K requirement into three $150K purchases to use SAP — is:',
            options: ['A legitimate use of simplified acquisition procedures', 'A violation of FAR 13.003(c) — requirements cannot be artificially split to circumvent competition or dollar thresholds', 'Permitted if the items are needed at different times', 'Only a problem if audited by DCAA'],
            correct: 1,
            explanation: 'FAR 13.003(c) explicitly prohibits splitting requirements into smaller purchases to avoid competition requirements or threshold limitations. This is a common compliance violation that auditors and inspectors general actively look for. The test is whether the items serve a single end purpose that should be acquired as one requirement — if so, they must be consolidated and competed appropriately.',
          },
          {
            id: 'q6',
            question: 'Which FAR clause replaces dozens of standard DFARS clauses when FAR Part 12 commercial item procedures are used?',
            options: ['FAR 52.215-2 (Audit and Records)', 'FAR 52.212-4 (Contract Terms and Conditions — Commercial Products) and FAR 52.212-5', 'DFARS 252.204-7012 (Cybersecurity)', 'FAR 52.222-26 (Equal Opportunity)'],
            correct: 1,
            explanation: 'FAR 52.212-4 and 52.212-5 are the streamlined commercial terms clauses that substitute for the full list of individual standard FAR clauses normally required. This is what makes commercial acquisitions so much faster — instead of reviewing 30+ clause flowdown requirements, the CO simply incorporates 52.212-4/5, which contain the essential terms in a single, commercial-friendly format.',
          },
          {
            id: 'q7',
            question: 'A sole source justification under FAR 6.302-2 ("unusual and compelling urgency") requires the PM to demonstrate:',
            options: ['The requirement is classified', 'There is an immediate danger to life, national security, or critical mission; and competition would cause unacceptable delay', 'The contractor is the only one in the world with the capability', 'The acquisition is below the simplified acquisition threshold'],
            correct: 1,
            explanation: 'FAR 6.302-2 urgency requires a genuine time-critical situation where competing the requirement would cause serious harm — not just inconvenience. The J&A must document the specific harm of delay, the limited period for the noncompetitive award, and a plan to compete follow-on requirements. "We didn\'t plan ahead" does not qualify as unusual and compelling urgency.',
          },
          {
            id: 'q8',
            question: 'A key OTA safeguard that prevents its use solely as a competition-avoidance tool for production is:',
            options: ['OTAs must be reviewed by GAO before award', 'Production OTAs require the prototype to have been successfully demonstrated AND the OTA must include at least one nontraditional contractor OR significant government cost-share', 'OTAs are automatically cancelled after 2 years', 'All OTAs must be competitively awarded through a public notice'],
            correct: 1,
            explanation: 'The nontraditional contractor OR government cost-share requirement prevents traditional defense contractors from simply using OTA to avoid competition. The "successful demonstration" requirement ensures follow-on production is genuinely tied to demonstrated prototype results. Together, these safeguards are intended to prevent OTA from becoming a regulatory loophole for routine production contracting.',
          },
          {
            id: 'q9',
            question: 'Government Purchase Cards (GPCs) can be used without any competition requirement for purchases at or below:',
            options: ['$2,500', '$10,000', '$25,000', '$50,000'],
            correct: 1,
            explanation: 'The micro-purchase threshold is $15,000 (FAR 13.201) — purchases at or below this amount may be made with a GPC by any authorized cardholder without a competition requirement. Above $15K, SAP competition standards apply. Above $350K (SAT), full competition and documentation requirements apply.',
          },
          {
            id: 'q10',
            question: 'Which statement best describes the relationship between OTA and FAR?',
            options: ['OTAs are a type of contract governed by FAR Part 16', 'OTAs are agreements (not procurement contracts) that operate outside the FAR — they are governed by their own negotiated terms and the authorizing statute (10 USC 4022)', 'OTAs are subject to FAR but exempt from DFARS', 'OTAs must be converted to FAR contracts within 180 days'],
            correct: 1,
            explanation: 'OTAs are explicitly not procurement contracts and are not subject to the FAR or DFARS. They are governed by the statutory authority (10 USC 4022 for prototype and production), the negotiated agreement terms, and any agency-specific OTA guidance (like the OSD OTA Guide). This is the source of their flexibility — and the reason they require careful legal and policy oversight.',
          },
          {
            id: 'q11',
            type: 'drag_match',
            question: 'Match each acquisition path to its best use case:',
            options: [],
            correct: 0,
            explanation: 'Matching the acquisition strategy to the requirement type is a core PM competency. Traditional FAR contracts for complex regulated programs. FAR Part 12 for genuine commercial products. OTA for innovative prototypes with nontraditional contractors. SAP for small routine purchases. Each path exists to serve a specific need — using the wrong path creates legal, financial, and oversight risk.',
            pairs: [
              { left: 'Traditional FAR/DFARS Contract', right: 'Complex defense system requiring cost reimbursable R&D and CAS compliance' },
              { left: 'FAR Part 12 Commercial', right: 'Cloud services or COTS software sold commercially without modification' },
              { left: 'Other Transaction Authority (OTA)', right: 'AI prototype with Silicon Valley startup that refuses FAR compliance' },
              { left: 'Simplified Acquisition Procedures', right: 'Routine supplies purchase of $180K for program support' },
            ],
          },
          {
            id: 'q12',
            type: 'drag_order',
            question: 'Order these acquisition paths from MOST regulated/slowest to LEAST regulated/fastest:',
            options: [],
            correct: 0,
            explanation: 'Traditional FAR/DFARS contracts carry the full regulatory burden — CAS, DFARS business systems, certified cost data, competition requirements. FAR Part 12 is faster with reduced clause requirements. OTA eliminates FAR/DFARS entirely. SAP is streamlined for sub-SAT buys. Micro-purchases are immediate with no competition required. The trade-off: less regulation means less accountability — use the appropriate level for the risk.',
            orderedItems: [
              'Traditional FAR/DFARS Contract (full CAS, DFARS, TINA, competition)',
              'FAR Part 12 Commercial Item (reduced clauses; no CAS; no certified cost data)',
              'Other Transaction Authority (no FAR/DFARS/CAS; negotiated terms only)',
              'Simplified Acquisition Procedures (below $350K; three quotes; minimal docs)',
              'Micro-Purchase / Government Purchase Card (below $15K; no competition required)',
            ],
          },
        ],
      },
